### ISSUE TITLE
Custom Fonts not available in IE11

### ISSUE THREAD

**Issue by dweiger** [webcomponents/webcomponentsjs#1041]
If I try to use a custom font with @fontface the font is not available in IE11. Works in all other Browsers.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!

**Comment by sampi** [comment]
@dweiger 

I had a similar issue, where I was using CSS Custom Properties to define the `font-family` and it would work everywhere except IE11.

I realized that ShadyCSS was trying to shim those Custom Properties, even though I had PostCSS do it for me.

The solution was to disable ShadyCSS shimming Custom Properties by putting this code before loading the polyfills:
```html
<script>
	// Don't shim CSS Custom Properties on IE11
	if (!window.Promise) {
		window.ShadyDOM = { force: true };
		window.ShadyCSS = { nativeCss: true };
	}
</script>
```
