### ISSUE TITLE
Fix Issues with Symbol Polyfill in IE 11

### ISSUE THREAD

**Issue by alienriver49** [webcomponents/webcomponentsjs#1047]
Per https://github.com/es-shims/get-own-property-symbols/issues/13, webcomponentsjs should either look for a different polyfill for Symbol or remove the 'use strict' from the top of the bundled code by setting rollups useStrict config option to false. If going with the first option, core-js would be a good alternative.

**Comment by alienriver49** [comment]
I'm sorry about opening Yet Another Symbol polyfill issue. :anguished: I will work on a pull request for you guys to see if we can get this resolved for good.

**Comment by TimvdLippe** [comment]
We switched to this polyfill in #1005. At this point, I fear we can not simply fix this and you would need to resort to #1021 so that you can choose the other polyfills that work for your application.

**Comment by alienriver49** [comment]
Alright, sounds good. I'll look into just loading the core-js Symbol polyfill first and see if that will work as a long-term solution. Thanks!

**Comment by ljharb** [comment]
I'm confused why you'd want rollup's `useStrict` option, since naively enabling strict mode on CJS code can break many things easily.

**Comment by kevinpschaaf** [comment]
To be clear, it's not rollup, but rather closure compiler that's used to compile and bundle the polyfill bundles; the current settings assume all code we're bundling conforms to strict mode hence the top-level strict mode setting -- afaik this one polyfill which was recently added is the only one the relies on non-strict behavior.  We can simply put closure in non-strict mode for the entire bundle (it appears closure doesn't have a way to preserve granular strict mode settings per closure, unfortunately -- its minification is very aggressive, which is why we use it) -- but we're inclined to not change that and work around the loose requirement for this one polyfill.

AFAICT the fact that that polyfill relies on loose mode to _not_ throw there is actually a bug, since in loose mode `toString` necessarily gives the wrong answer when called against `null`/`undefined`, so I filed another issue just on correctness grounds: https://github.com/es-shims/get-own-property-symbols/issues/16.

In the meantime, we can just work around the issue in our `symbol.js` fixup file for the time being to make `toString` compatible with strict mode.
