### ISSUE TITLE
The order of attached and property changed changes when tokenList is used to change class

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponentsjs#107]
<a href="https://github.com/frankiefu"><img src="https://avatars.githubusercontent.com/u/116360?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [frankiefu](https://github.com/frankiefu)**
_Tuesday Mar 11, 2014 at 17:03 GMT_
_Originally opened as https://github.com/Polymer/ShadowDOM/issues/400_

---

x-bar has the following definition.

``` html
<polymer-element name="x-bar" attributes="active">
  <template>
  </template>
  <script>
    Polymer('x-bar', {
      attached: function() {
        console.log('x-bar: attached');
      },
      activeChanged: function() {
        console.log('x-bar: activeChanged', this.active);
      }
    });
  </script>
</polymer-element>
```

I have x-bar inside template repeat like this:

``` html
<template repeat="{{ message in messages }}">
  <x-bar active></x-bar>
</template>
```

output:

```
x-bar: attached
x-bar: activeChanged
```

But when tokenList is used to change class, the order of attached and activeChanged changes under ShadowDOM polyfill (In native ShadowDOM the same order is maintained):

``` html
<template repeat="{{ message in messages }}">
  <x-bar active class="{{ {approval: message.approval} | tokenList }}"></x-bar>
</template>
```

output:

```
x-bar: activeChanged
x-bar: attached  
```

jsbin:
http://jsbin.com/melaxoxu/1/edit

We probably shouldn't rely on the order, but native ShadowDOM and polyfill should behave the same if it is possible.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
