### ISSUE TITLE
ie 11 example page

### ISSUE THREAD

**Issue by cekvenich** [webcomponents/webcomponentsjs#1087]
Is there an IE 11 example of a simplest page loading a simplest component? With a loader that auto loads needed pollyfils?
With same html that works on modern browsers?

Not how to make one, not what I should do: but an example of everything working.

**Comment by jfehrman** [comment]
I've also tried for a long time to get this working in IE11 and I can't.
```html
<script src="../node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js" charset="utf-8"></script>
<script src="../dist/ez-validation-input.js"></script>
```
Followed by using my component just doesn't work.
```html
<input is="ez-validation-input" required="true" regex="[0-9]"></input>
```
I've also tried changing the second script import tag to be of type module and no luck.
I am building my component with webpack with babel and babel-env so that I can use modern ES6 syntax.  Works in Chrome no problem, but doesn't work in IE.

**Comment by cekvenich** [comment]
@jfehrman I got it to work:
- https://github.com/metabake/MetaCake/tree/master/metaCake/webC1
That has a index.html and the .js that is the component.
Runs on ie 11 and modern browsers. 

I plan to write a tutorial. But in the mean time please ask in case you need help.

**Comment by cekvenich** [comment]
@jfehrman Article posted: https://github.com/metabake/MetaCake/tree/master/metaCake/webC1

Would be happy with any feedback.
