### ISSUE TITLE
Content selector fail on Internet Explorer when splitting over 2 content containers

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponentsjs#114]
<a href="https://github.com/stevehansen"><img src="https://avatars.githubusercontent.com/u/2143488?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [stevehansen](https://github.com/stevehansen)**
_Monday Sep 29, 2014 at 12:30 GMT_
_Originally opened as https://github.com/Polymer/ShadowDOM/issues/513_

---

When using light DOM to split the children over 2 content containers fail on IE11.

```
<div active>
  <content select=":not([disabled])"></content>
</div>
<div disabled>
   <content select="[disabled]"></content>
</div>
```

It works when the element is attached, but when the attribute changes (see example) the element will just disappear from the DOM tree.

http://jsbin.com/kerawe/2/edit?html,output

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
