### ISSUE TITLE
MutationObserver polyfill can't observe Shadow Roots in ShadowDOMPolyfill

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponentsjs#119]
<a href="https://github.com/azakus"><img src="https://avatars.githubusercontent.com/u/46725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [azakus](https://github.com/azakus)**
_Wednesday May 15, 2013 at 21:21 GMT_
_Originally opened as https://github.com/Polymer/MutationObservers/issues/7_

---

Mutations to a ShadowRoot will not trigger the MutationObserver in IE
Test case: azakus/ShadowDOM@d822c0f

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
