### ISSUE TITLE
[HTML Imports] @import "url"

### ISSUE THREAD

**Issue by nevir** [webcomponents/webcomponentsjs#123]
The style path rewriter doesn't pick up on the `@import "url"` syntax (it [expects `url()` style imports](https://github.com/webcomponents/webcomponentsjs/blob/master/src/HTMLImports/path.js#L13) only)

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
