### ISSUE TITLE
Error events in Chrome and Firefox

### ISSUE THREAD

**Issue by kgryte** [webcomponents/webcomponentsjs#138]
When using web component tester to run unit tests on Polymer components, I encountered the following stack trace in Firefox.

```
 browser.js:7702
"[object CustomEvent] (undefined:undefined)
       EventTarget.prototype.dispatchEvent at /webcomponentsjs/webcomponents.js:1345
                                utils.fire at /polymer/polymer.js:9023
        [1]</foo.prototype.attrChanged at /my-component/build/js/script.js:1597
                   properties.invokeMethod at /polymer/polymer.js:9377
          properties.notifyPropertyChanges at /polymer/polymer.js:9366
                Observer.prototype.report_ at /polymer/polymer.js:4912
        CompoundObserver.prototype<.check_ at /polymer/polymer.js:5318
  global.Platform.performMicrotaskCheckpoint at /polymer/polymer.js:4973
                                   flush/< at /polymer/polymer.js:8174
                          atEndOfMicrotask at /polymer/polymer.js:8119
                           notifyObservers at /webcomponentsjs/webcomponents.js:578
                                    handle at /webcomponentsjs/webcomponents.js:523"
```

I do not see this in Chrome.

The difference appears to be in how Chrome and Firefox handle `error` events. The component I am testing performs type validation in the `attributeChanged` callback. If an assignment is not of the proper type, the method fires an `error` event with an `event.detail` set to a `TypeError`.

``` javascript
   ...
   attrChanged: function( oldVal, newVal ) {
    var err;
    if ( typeof newVal !== 'string' ) {
        err = new TypeError( 'attr::invalid assignment. Must be a string. Value: `' + newVal + '`.' );
        this.fire( 'error', err );
        this.attr = oldVal;
        return;
    }
   },
   ...
```

In Chrome, firing the `error` event does not cause any problems during testing. I am able to validate that an invalid assignment results in the firing of an `error` event without the test failing.

``` javascript
  ...
  it( 'should emit an `error` if set to a non-string', function test( done ) {
    el.addEventListener( 'error', onError );
    el.attr = 1234;
    function onError( evt ) {
      assert.instanceOf( evt.detail, TypeError );
      el.removeEventListener( 'error', onError );
      done();
    }
  });
  ...
```

In Firefox, however, firing an `error` event causes the test to fail and the above stack trace. If I change the event to `errored`, then the test passes in Firefox.

Why the difference in behavior? I am guessing part of the issue may be having to use the webcomponents polyfill in Firefox, where in Chrome observers are natively supported (?).

Is this a bug in the polyfill? Any other workarounds, which are not renaming the `error` event to something other than `error`?

**Comment by nithiz** [comment]
I am having the exact same issue (also using Polymer). I am using window.addEventListener to listen to error events coming from anywhere within the application. First it worked, now it fails.

However, using the on-error attribute everything works fine... Weird...

**Comment by nithiz** [comment]
I guess Firefox did reserve that event, renaming is the only option now i guess.. :/

https://developer.mozilla.org/en-US/docs/Web/Events/error

**Comment by garlicnation** [comment]
on-error is polymer's wrapper for the error event. I'm not familiar with the exact codepath, but I believe it works because we hide the browser-level error event and provide a nicer interface to it.

webcomponentsjs won't do anything to prevent firefox from handling the error event as it sees fit, so I think the right choice here is to rename the event.

**Comment by mazswojejzony** [comment]
I have the same issue when running Web Component Tester test suite. One of my components under tests uses `<iron-ajax>` element which happens to report errors via `on-error` event.

I was able to work-around this problem using sinon fake server but still it would be great to test scenarios when server is not reachable at all and `<iron-ajax>` on-error fires.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
