### ISSUE TITLE
Element upgrades are async in some situations

### ISSUE THREAD

**Issue by jakemac53** [webcomponents/webcomponentsjs#169]
Specifically, when setting innerHTML the upgrade is async. Thus if you set the innerHTML and then query right away for something you expect to be a custom element it won't be upgraded.

**Comment by jmesserly** [comment]
This is sort of "by polyfill design" ... CustomElements uses a MutationObserver because it has much less overhead. It would be technically possible to fix this by doing ShadowDOM level tricks, but the overhead of that would be pretty significant (since innerHTML can't be patched properly until Safari fixes their DOM accessor bug).

One thing we could do is fix it in webcomponents.js but not webcomponents-lite.js. In the former, ShadowDOM already knows synchronously that a mutation happened.

But personally, my vote would be to leave CE as is. Its performance is really good right now thanks to these kind of tradeoffs. And the workaround of calling `CustomElements.upgrade` or waiting a tick for upgrade to happen doesn't seem too bad to me

**Comment by jakemac53** [comment]
Thats good to know about CustomElements.upgrade, I will leave it up to you. This can definitely be somewhat of a gotcha (cost me around an hour of debugging yesterday), but I agree with the tradeoff.

I think the more important thing is somehow messaging this to developers so they don't spend hours trying to debug something that is actually working as designed... but at the same time I don't really know the best way to do that. Maybe just a note in the readme, at least thats a good start.

**Comment by lazd** [comment]
From my experience using `webcomponents.js`:

Assuming you have something like:

```html
<div id="container>
  <coral-progress id="component"></coral-progress>
</div>
```

`CustomElements.upgradeAll(container)` can be called on a the `<div id="container">` element and will upgrade all descendants of that element that need upgrading. You can also call it directly on a component `CustomElements.upgradeAll(container)` and it will do the same.

`CustomElements.upgrade(component)` will upgrade the passed component and all of it's descendants that need upgrading, but `CustomElements.upgrade(container)` will do nothing.

Waiting a tick works fine, but if you're on a browser that doesn't support `requestAnimationFrame` the easiest thing to do is to call `CustomElements.upgrade(container)` and know that every component is now ready for use.

Also, if you're waiting for the initial markup in the document to be upgraded, you can listen to the `WebComponentsReady` event on `window` and can be confident that all components in the DOM are ready for use.

**Comment by TimvdLippe** [comment]
This appears to be fixed: http://jsbin.com/xirahix/edit?html,console,output
