### ISSUE TITLE
CSP & Firefox

### ISSUE THREAD

**Issue by lukeshiru** [webcomponents/webcomponentsjs#171]
When loading a component with CSP in Firefox Developer Edition (currently in version 37.0a2), for use with Polymer, I get the following error:

```
Content Security Policy: The page's settings blocked the loading of a resource at data:text/javascript;charset=utf-8,...
```

Presumably, this error comes from the way you implemented the generateScriptDataUrl/addElementToDocument to append the imported component to the document, parsing the HTML as a JS or something like that.

**Edit:**

Adding **data:** to the **script-src** CSP header is the only way to make it work, but this is a significant hole in the security, for obvious reasons.

**Comment by indolering** [comment]
I don't remember running into this bug when enabling CSP, perhaps it has been fixed?

**Comment by ludflu** [comment]
We just ran into this issue with Firefox and also Safari.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!

**Comment by lukeshiru** [comment]
NP, I'm not even using Polymer anymore. This issue was there before Firefox Quantum, so maybe is fixed. Thank you, @TimvdLippe !

**Comment by d4l3k** [comment]
I just ran into this issue under Firefox 60 with webcomponents v1.0. I don't believe it's possible to reproduce this with jsBin since it requires the CSP header. Adding data: fixed it.

```
content-security-policy: default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; img-src 'self' https://i.imgur.com
```

**Comment by rozzamozza** [comment]
Adding data: for script sources is not secure...
