### ISSUE TITLE
getTransformToElement not working because it tries to use a wrapped item with the native function

### ISSUE THREAD

**Issue by rd-secretstuff** [webcomponents/webcomponentsjs#192]
getTransformToElement doesn't work because it will try and call the native function with a wrapped object as a parameter.

For example :

``` javascript
var Children = mySVGElement.children,
for (var Index = 0; Index < Children.length; Index++)
{
    // this line fails because mySVGElement is a wrapped object 
    // firefox log message = TypeError: Argument 1 of SVGGraphicsElement.getTransformToElement does not implement interface SVGGraphicsElement.
    Children[Index].getTransformToElement(mySVGElement); 
    // this line works
    Children[Index].getTransformToElement(mySVGElement.__impl4cf1e782hg__); 
}
```

This seems to happen because the getTransformToElement is implemented like this :

``` javascript
return this.__impl4cf1e782hg__." + name + ".apply(this.__impl4cf1e782hg__, arguments);
```

The above implementation tries to call the native version directly using the native objects, but there is no code that tries to unwrap any of the arguments passed in to the function.

**Comment by rd-secretstuff** [comment]
For anyone running into this problem also, this is my current work around

```javascript
    // include this after webcomponents.js
    // if the shadow dom polyfill is used...
    if (window.ShadowDOMPolyfill)
    {
        var SVGElement = document.createElementNS("http://www.w3.org/2000/svg", "g");
        SVGElement.__proto__.getTransformToElement = function getTransformToElement(p_Element)
        {
            return window.ShadowDOMPolyfill.unwrap(this).getTransformToElement(window.ShadowDOMPolyfill.unwrap(p_Element));
        };
    } 
```

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
