### ISSUE TITLE
IE11 + Facebook SDK

### ISSUE THREAD

**Issue by Mikanoshi** [webcomponents/webcomponentsjs#208]
InvalidCharacterError in webcomponents.js
Works in all other browsers.
Example: http://sysprofile.ru/test2.html

**Comment by johnnyiller** [comment]
I'm seeing the same thing, not really sure what the issue is.  Thinking it might be a facebook issue.

**Comment by garlicnation** [comment]
This is a bug in Facebook's SDK.

They're calling createElement with angle brackets, which IE hasn't supported since IE9.

https://msdn.microsoft.com/en-us/library/ie/ff986077(v=vs.85).aspx

![screen shot 2015-03-06 at 7 28 53 pm](https://cloud.githubusercontent.com/assets/1105965/6539869/119a9b54-c437-11e4-9a31-2eff73fba018.png)

**Comment by Mikanoshi** [comment]
There is ``if ... else ...`` block, maybe it is for backward compatibility and the problem is with something else? Facebook team says they don't support this 3rd party library. I doubt they'll fix this, because SDK works fine without webcomponents.

**Comment by garlicnation** [comment]
@sorvell WDYT? How much do you guess the weight of supporting angle brackets is? It seems like the API is much more prone to security issues(we would need to parse the element definition to some level).

**Comment by johnnyiller** [comment]
I fixed this problem for our site.  Basically I re-wrap the createElement function to behave different when it sees the "<iframe...."  good luck.  

http://www.jefferydurand.com/facebook/sdk/webcomponents/ie11/bug/2015/03/07/fb-init-webcomponentsjs-ie11-InvalidCharacterError.html
