### ISSUE TITLE
0.5.5 breaks MutationObserver nodeValue observation in Firefox and Safari

### ISSUE THREAD

**Issue by yyx990803** [webcomponents/webcomponentsjs#213]
As the title said, jsfiddle here: http://jsfiddle.net/e2u6k4nc/3/
This completely breaks interop with other libraries that also rely on MutationObservers.

**Comment by jmesserly** [comment]
probably ShadowDOM polyfill. I'm not seeing any problem in Firefox though.
it works if you use `textContent` instead of `nodeValue`
SD polyfill does not implement nodeValue. It would be an easy fix, if you're up for it:
https://github.com/webcomponents/webcomponentsjs/blob/master/src/ShadowDOM/wrappers/CharacterData.js#L28

**Comment by jmesserly** [comment]
a more accurate title for this is probably "ShadowDOM polyfill does not support nodeValue"

**Comment by yyx990803** [comment]
I think there's another issue here, because the fiddle works as intended without the polyfill, using the native MutationObserver provided by the browsers, but breaks when the polyfill is included. Shouldn't the polyfill leave the native implementation untouched if the browser already supports it?

**Comment by garlicnation** [comment]
@jmesserly Would #225 be sufficient to fix this?

**Comment by addyosmani** [comment]
Closing as fixed in https://github.com/webcomponents/webcomponentsjs/pull/225
