### ISSUE TITLE
path.js: media query not supported in @import rules

### ISSUE THREAD

**Issue by vicb** [webcomponents/webcomponentsjs#216]
@import rules could be [media dependent](http://www.w3.org/TR/CSS21/cascade.html#at-import):
`@import url("bluish.css") projection, tv;`

However the regexp in [path.js](https://github.com/webcomponents/webcomponentsjs/blob/4c5f21610c6cea02c74beaa3a25cd8075807ce31/src/HTMLImports/path.js#L13) is `/(@import[\s]+(?!url\())([^;]*)(;)/g`

The media query will be matched as part of the url (ie anything before ";")

**Comment by vicb** [comment]
One RegExp that could work is `(@import[\s]+(?!url\\())[\'"]([^\'"]*)[\'"](.*;)`

I can't find how to test this, I would have sent a PR otherwise.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
