### ISSUE TITLE
 Can't find variable: Window - PhantomJS

### ISSUE THREAD

**Issue by valtido** [webcomponents/webcomponentsjs#239]
I am using PhantomJS (for obvious reason ... testing) and having a little trouble injecting the webcomponents I get the following error.

```
ERROR [karma]: ReferenceError: Can't find variable: Window
at http://localhost:9876/base/bower_components/webcomponentsjs/webcomponents.min.js?4df003d683d116afbe59cee4eb03a58c5e57515a:11

```

I am using `PhantomJS v1.9.7` at the moment

I know you don't support this, but it would help alot so it's not sooo annoying to wait for chrome to pop-up it's a little distracting.

**Comment by garlicnation** [comment]
Can you run against the non-minified JS and print out a stacktrace of the failure?

**Comment by valtido** [comment]
I get the following...

They are not even the same... this is weird.

```
ERROR [karma]: SyntaxError: Parse error
at http://localhost:9876/base/bower_components/webcomponentsjs/webcomponents.js?4d42277f28e0f421335ad084cf5df49c838ab7a5:1956
```

**Comment by valtido** [comment]
after reading about this article on [StackOverflow](http://stackoverflow.com/questions/14905664/getting-more-information-from-phantomjs-syntaxerror-parse-error-message) I followed the instructions and got the following:

```

$ node bower_components/webcomponentsjs/webcomponents.js
C:\Users\vcaushi\dev\jom\bower_components\webcomponentsjs\webcomponents.js:11
window.WebComponents = window.WebComponents || {};
^
ReferenceError: window is not defined
    at Object.<anonymous> (C:\Users\vcaushi\dev\jom\bower_components\webcomponentsjs\webcomponents.js:11:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by krampstudio** [comment]
I'm having the same issue when I inject the polyfill in PhantomJS using karma. But I don't have the issue with Firefox. 
This is not an error from the polyfill itself but the way it is loaded in PhatomJS, according to this [thread](http://stackoverflow.com/questions/15302928/cant-find-variable-phantomjs#answer-15307220) the polyfill has to be loaded in `evaluate` .
And the result you get in your last test is because node runs on the server, it has no `window` object.

**Comment by addyosmani** [comment]
Does running the polyfill via `evaluate` work, or is it causing the same set of issues?

**Comment by valtido** [comment]
Couldn't a wrapper like jQuery does work for both node and browsers?

```
(function(window){
  ...
})(this)
```

OAN: I have no idea what you are referring to @krampstudio or how to implement it, my impression is that I should change "phantom js" or something...?

**Comment by krampstudio** [comment]
@valtido I'm referring to the section "code evaluation" of the [PhantomJS Doc](http://phantomjs.org/quick-start.html). For example, my problem was to try to load it using karma and browserify as a test dependency.

@addyosmani I was able to go further but the polyfill isn't compatible with the  PantomJS 1.9.x branch. It had failed while parsing [getter/setter of the URL polyfill](https://github.com/webcomponents/webcomponentsjs/blob/master/src/URL/URL.js#L473).

**Comment by bedeoverend** [comment]
I've got the same issue - currently on Polymer 0.8, (so webcomponents-lite, though same problem with full webcomponents polyfill) and PhantomJS 1.9.8.

It looks like its calling `import.loaded.bind(...)`, PhantomJS 1.9.x doesn't support the `bind`, as discuss in [this issue](https://github.com/ariya/phantomjs/issues/10522) so @valtido it looks like PhantomJS 2 should have resolved it, but @krampstudio [karma hasn't](https://github.com/karma-runner/karma-phantomjs-launcher/issues/56) included it yet, so might be worth using a `bind` [polyfill](https://github.com/kdimatteo/bind-polyfill) / [shim](https://github.com/tschaub/karma-phantomjs-shim) until they get around to using PhantomJS 2
Just installed the shim, looks like its working.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
