### ISSUE TITLE
Page load performance/hangs

### ISSUE THREAD

**Issue by oswaldofreitas** [webcomponents/webcomponentsjs#242]
I have a project using generator-polymer (so, using vulcanize and other optimizations with gulp) and when I run it in Safari I have a intermittent issue loading the app. After 2 seconds the page hangs and back after about 14 sec. The timeline inspector don't show nothing in this "pause", so I can't tell you where is the problem in my project. I could send you the entire project code if you need to analyze in a private message.

**Comment by robdodson** [comment]
I would try to strip the project down to the simplest pieces, see if those render with OK performance, and then add sections of your app back until you discover the problem. If you can narrow it down like that it will make it much easier for us to debug.

**Comment by garlicnation** [comment]
@oswaldomilet We'd be happy to take a look at the project if you're able to provide two versions of it:

- A vulcanized, but non-uglified/optimized/comment-stripped version of your app, since it's unlikely that page size is causing hangs of 14s
-  Non-vulcanized/minified version(including your libraries).

**Comment by oswaldomilet** [comment]
@garlicnation, I sent the little project to your email...

Note that to simulate the problem, you have to clear browser cache before each refresh.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
