### ISSUE TITLE
webshim html5 form validation polyfill doesn't run w/ 0.5.5 / 0.6 webcomponents.js present

### ISSUE THREAD

**Issue by erutan** [webcomponents/webcomponentsjs#255]
I've tried removing all options and just loading the forms portion of https://afarkas.github.io/webshim/demos/index.html#Forms-forms, no dice. forms-ext works (at least the date input polyfill).  I've forked a sample fiddle from webshim to show this (originally fails in a local app I'm developing). Using https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.6.0/webcomponents.min.js has the same result. No JS errors in dev console.

https://afarkas.github.io/webshim/demos/demos/forms.html#Locale-customMessages webshim functionality in question.

http://jsfiddle.net/trixta/9859C/light/ (original example)

http://jsfiddle.net/erutan/Lso7gc4c/1/ (as above with https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.5.5/webcomponents.min.js included as external dependency)

Not entirely sure whether this should be here or at webshim (I'll copy the issue in both).

**Comment by erutan** [comment]
via webshim repo:

This is a webcomponents issue, just run this code, with and without webcomponents:

<form id="form" class="ws-validate">
    <input required=""  />
    <input type="submit" />
</form>
<script>
    $(document).on('special', function(){
        console.log('document');
    });
    $(document.body).on('special', function(){
        console.log('body');
    });
    $('form').on('special', function(){
        console.log('form');
    });
    $('input').eq(0).trigger('special');
</script>

**Comment by addyosmani** [comment]
As per https://github.com/webcomponents/webcomponentsjs/issues/49, you may need to wrap your code as follows:

ˋˋˋ
// The fix seems to be to wrap document and/or document.body. ex:

(function(document) {
  // add your jquery handlers here...
  $(document).on('click', ...);
})(wrap(document));
ˋˋˋ

as ShadowDOM wrappers will otherwise break your code. I recommend attempting this fix or otherwise using the webcomponents-lite.js build included in our releases which doesn't use ShadowDOM.

**Comment by erutan** [comment]
Thanks for checking things out. I had it wrapped before, and the live form validation custom messages work in Chrome but not Safari/Firefox, so I'll assume it has to do with Shadow DOM.

I'm designing + prototyping an (internal) application using Polymer, for externally facing ones we can't take the IE requirements hit so for the near future aren't using web components. I can live without the custom validation messages in this case (moreso than forcing everyone to use Chrome), and my JSfu isn't quite up to hacking polyfill frameworks. :)

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
