### ISSUE TITLE
Why IE shows different?

### ISSUE THREAD

**Issue by oswaldofreitas** [webcomponents/webcomponentsjs#260]
Please, go to www.info2bits.com and navigate to "SERVIÇOS" page. Why IE don't stretch the 3 columns height and other browsers do? I'm using section min-height 100%
- I just updated to 0.6

**Comment by addyosmani** [comment]
Can you provide us with some more information? e.g what version of IE is this failing in? It would also be super-useful if you could distill the above into a reduced test case on jsbin so we can dig into what's breaking for you.

**Comment by oswaldomilet** [comment]
![ie version](https://cloud.githubusercontent.com/assets/10772835/6867222/83baa24c-d45e-11e4-9b71-8211f692007c.JPG)
Next, I'll try to reproduce in jsbin...

**Comment by oswaldomilet** [comment]
I tried jsbin, but what is missing in the code to show "TEST" in output?

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.6.0/webcomponents.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/polymer/0.5.5/polymer.min.js"></script>
</head>
<body>
  <myComponent></myComponent>
</body>
</html>

<polymer-element name="myComponent" noscript>
  <template>
    <style></style>
    <span>TEST</span>
  </template>
</polymer-element>
```

**Comment by robdodson** [comment]
@oswaldomilet you can use this as the base for your jsbin:

http://jsbin.com/xutak/1/edit?html,output

**Comment by oswaldomilet** [comment]
Dash was missing from component name and I changed CDN to take from polymer site, thanks @robdodson

**Comment by oswaldomilet** [comment]
I did it in Plunker, maybe just some little extra code remain, but I guess it's simple.

[Here is the preview!](http://embed.plnkr.co/gzkOjGSy22UeVcCEhnl1/preview)

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Opera
- [ ] IE

![issue polymer](https://cloud.githubusercontent.com/assets/10772835/6883092/e860efd4-d57c-11e4-9b38-8a2dc6be454d.JPG)

**Comment by addyosmani** [comment]
Hmm. Unable to repro in IE11 here:

![screen shot 2015-03-31 at 18 06 46](https://cloud.githubusercontent.com/assets/110953/6924486/c06b9550-d7d0-11e4-98e7-88333cc3d13d.png)

**Comment by oswaldomilet** [comment]
I'm using latest version of IE on Windows 8, different from your version (guess Windows 10)

**Comment by addyosmani** [comment]
I believe I have a Windows 8 image handly too (yeah, I'm using Windows 10 atm). Will retest and get back to you.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
