### ISSUE TITLE
webcomponents.js v0.5.5 not work for Project Spartan

### ISSUE THREAD

**Issue by ToshihiroGoto** [webcomponents/webcomponentsjs#263]
webcomponents.js Line:4525
Error is CSS value "initial"?

Bug in the Project Spartan?

**Comment by addyosmani** [comment]
Could you please share a jsbin which fails in Spartan so we can try reproducing it?

**Comment by ToshihiroGoto** [comment]
Error sample is not created , but I did not run in the following sites , etc. .

https://www.polymer-project.org/0.5/
Chrome Dev Editor - Polymer Template 

It may be spartans bug ...

Test Environment:
Windows 10 TP Build 10049 - Project Spartan Browser

**Comment by takueof** [comment]
:+1:

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
