### ISSUE TITLE
TypeError: this.__impl4cf1e782hg__ is undefined in Firefox

### ISSUE THREAD

**Issue by edrachev** [webcomponents/webcomponentsjs#265]
I use Polymer 0.5.5 and when I create custom element with attributes="properties", I get "TypeError: this.**impl4cf1e782hg** is undefined" in webcomponents.js

My component:
&lt;polymer-element name="my-element" attributes="properties"&gt;
&nbsp;&nbsp;&lt;template&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;div&gt;&lt;/div&gt;
&nbsp;&nbsp;&lt;/template&gt;
&nbsp;&nbsp;&lt;script&gt;
&nbsp;&nbsp;&nbsp;&nbsp;Polymer('my-element', { })
&nbsp;&nbsp;&lt;/script&gt;
&lt;/polymer-element&gt;

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
