### ISSUE TITLE
TypeError: this.scopeSelector is not a function in webcomponents.js on FF 37 

### ISSUE THREAD

**Issue by Protoss78** [webcomponents/webcomponentsjs#266]
Today I've tested my polymer application for the first time on the latest Firefox 37.0 and got the following error message during startup:
TypeError: this.scopeSelector is not a function at  webcomponents.js:4440:25.
I'm using webcomponents.js version 0.5.5. 
The problematic line of code is marked on the screenshot here:
![bildschirmfoto vom 2015-04-02 13 16 30](https://cloud.githubusercontent.com/assets/4738976/6963025/8420526e-d93a-11e4-8845-699fd53b671a.png)

**Comment by addyosmani** [comment]
Can you try with webcomponents.js 0.6.0 and let us know if the same issue occurs?

**Comment by Protoss78** [comment]
Just tried it with 0.6.0 and ran into the same problem. Again the same line in the same method seems to cause this problem. In 0.6.0 it is at: webcomponents.js:4517:25

**Comment by Protoss78** [comment]
I just tried it again on Firefox 37.0.1 and saw the following warning message before the actual error appeared: 
"mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create" at  webcomponents.js:6346:6.

Not sure if that is somehow related.

**Comment by miriti** [comment]
Having the same with Firefox 39.0 and webcomponentsjs 0.6.3

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
