### ISSUE TITLE
Valid range throws IndexSizeError in custom elements  

### ISSUE THREAD

**Issue by eeid26** [webcomponents/webcomponentsjs#268]
This sample shows the error
http://jsbin.com/kasuwiragu/2/edit?html,output

This happens if you have `<content>` inside some other element in the shadow dom.
If you are running with chrome, remove the shadow flag from the webcomponents.js script tag and the native shadow implementation will make the selection as expected.

PR to fix this issue is
https://github.com/webcomponents/webcomponentsjs/pull/264

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
