### ISSUE TITLE
Custom Elements test disallowing `font-face` element fails on Chrome

### ISSUE THREAD

**Issue by sorvell** [webcomponents/webcomponentsjs#272]
According to [the spec](http://w3c.github.io/webcomponents/spec/custom/#dfn-custom-element-type), attempting to register a reserved element name should throw. The test which checks for this error is failing on Chrome 41-43.

**Comment by sorvell** [comment]
Quick test that shows no error on Chrome when defining `font-face` element:

http://jsbin.com/vukiwecoka/1/edit?html,console,output

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
