### ISSUE TITLE
Cannot Piecemeal Include CustomElements and HTMLImports on Browsers That Do Not Support MutationObserver

### ISSUE THREAD

**Issue by robliao** [webcomponents/webcomponentsjs#274]
Because both HTMLImports and CustomElements require MutationObserver (https://github.com/webcomponents/webcomponentsjs/commit/db138bc00cc8e3f05ba8755ab26dda83cd988225), they now require webcomponents-lite.js for browsers that do not supply MutationObserver.

If we're going to need webcomponents-lite.js, then we might as well include that and avoid the whole piecemeal HTMLImport and CustomElement individual includes since we're in a polyfilling situation anyways.

**Comment by garlicnation** [comment]
We should just add MutationObserver back in to those polyfills. I'll open up a PR.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
