### ISSUE TITLE
template.content.getElementById() not wrapped

### ISSUE THREAD

**Issue by kevincox** [webcomponents/webcomponentsjs#285]
If you have a template element, calling `.content.getElementById("id")` will return an unwrapped node.

**Comment by jmesserly** [comment]
yeah, it looks like this is a problem with all DocumentFragments, as I don't see them define getElementById like they should (spec: https://dom.spec.whatwg.org/#nonelementparentnode) ... instead only [ShadowRoot](https://github.com/webcomponents/webcomponentsjs/blob/c317fa5dc8a792c82c9fd7b47b9888c9696d4781/src/ShadowDOM/wrappers/ShadowRoot.js#L74) and [Document](https://github.com/webcomponents/webcomponentsjs/blob/3edbe7fe07270ef70da341d14ac80867ffc6e48a/src/ShadowDOM/wrappers/Document.js#L71) define it. Probably an easy fix in src/ShadowDOM/wrappers/DocumentFragment.js

**Comment by jmesserly** [comment]
oops, wrappers/DocumentFragment.js doesn't exist, instead it's handled in wrappers/generic.js

**Comment by jmesserly** [comment]
oh, I think the original idea was that getElementById was unimplemented, since it's kind of deprecated nowadays, and the main reason to use it for performance wouldn't apply to the polyfill ... anyway, I'm going to fix it on Document too, because the Document one I linked earlier is not respecting ShadowDOM scoping (as far as I can tell)

**Comment by jmesserly** [comment]
uploaded a PR #288 to fix this
