### ISSUE TITLE
HTMLImportsLoaded event never fires in FF if loaded programmatically

### ISSUE THREAD

**Issue by DestyNova** [webcomponents/webcomponentsjs#286]
According to the docs, the appropriate way to load a child document involves listening for the HTMLImportsLoaded event when adding a link object to the document head.

This seems to work if I place HTMLImports.min.js in the parent document's head section, but not if I add it to the head later programmatically.

I've set up an example testcase [here](http://computing.dcu.ie/~omacfh/html-imports/testcase-loading-from-js-should-work/).

Please let me know if I'm doing this all wrong!

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!

**Comment by DestyNova** [comment]
Well, to be fair I *did* provide a live reproduction with the most recent version of the polyfill as of 3 years ago when I filed the bug :laughing: in any case, that project is long since dust and I'm sure the bug was fixed at some point since then.
