### ISSUE TITLE
Revisit CustomElements polyfill in absence of native HTML Imports

### ISSUE THREAD

**Issue by azakus** [webcomponents/webcomponentsjs#289]
Mozilla is trying to test Polymer with native Custom Elements, but we force the Custom Elements polyfill for timing reasons.

We should figure out what the issues are and provide Mozilla a way to test with native Custom Elements.

**Comment by garlicnation** [comment]
Tested firefox w/ webcomponents flag enabled using ShadowDOM then HTMLImports polyfills. 0.5 doesn't quite work(renders initally OK but restampting templates is wonky but isn't giving me any errors either.) Trying to replicate that in the webcomponents built version results in different errors.

Do we know if 0.5 is a requirement, or can I try to make this work with 0.8 instead?

**Comment by azakus** [comment]
Let's see if 0.8 will work. That may be enough for them anyway.

**Comment by arthurevans** [comment]
Ping @garlicnation. Just wondering about the status of this one (it comes up occasionally as a bug on the docs site, because people have the experimental webcomponents flag enabled on Firefox. Among other things, this does odd things to the icons on the site.)

**Comment by arthurevans** [comment]
@garlicnation @azakus we're still getting reports from people trying to use Polymer (or browse polymer-project.org) with the experimental webcomponents flag enabled.

**Comment by atotic** [comment]
Did a little digging here. Initially, nothing showed up when I enabled the flag because HTMLImports were not polyfilled. IMPORT_LINK_TYPE was defined, but they were not working. Once I got passed this, got a lot of CSS errors such as:
Unknown pseudo-class or pseudo-element 'host'.  Ruleset ignored due to bad selector.
Expected declaration but found '@apply'.  Skipped to next declaration.
Page showed up without any recognizable styles.

**Comment by alequint** [comment]
I had Firefix 31.8 and tested my application with Polymer... regardless if dom.webcomponents.enabled flat was true or false, it worked great. Then I migrate to FF 38... now it seems the webcomponents flag is taking effect, because when I have it "true", I cannot even enter in the page. But when I set it to "false", everything works great with my components. Is this property working only from a particular version of FF or ????

**Comment by christian-beckmann** [comment]
Firefox 46, Polymer 1.0 gets an blank page - without errors in console, when dom.webcomponents.enabled true.

**Comment by arthurevans** [comment]
This is a documented incompatibility with Firefox's experimental web component support:

Firefox currently supports some of the v0 web component APIs behind a flag. Polymer does not work correctly with this flag enabled, because of an incompatibility with the web components polyfills.

(This text is at the very end of the Polymer browser compatibility page: https://www.polymer-project.org/1.0/docs/browsers)

**Comment by TimvdLippe** [comment]
This should now be resolved with the webcomponents-loader.
