### ISSUE TITLE
The way webcomponents/shadowdom splits text nodes does not allow ranges to be adjusted by the browser

### ISSUE THREAD

**Issue by eeid26** [webcomponents/webcomponentsjs#291]
Without using webcomponents, when you have a start or end container in a Range pointing to a text node and you call Text.splitText https://developer.mozilla.org/en-US/docs/Web/API/Text/splitText, browsers adjust all ranges if needed to make them valid ranges. (The way the range is adjusted is different between browsers)

Because Text,js in the shadow dom splits the Text without calling Text.splitText, all ranges do not get fixed properly and they become invalid ranges

The implementation of splitText in shadow dom is 

``` javascript
      offset = toUInt32(offset);
      var s = this.data;
      if (offset > s.length)
        throw new Error('IndexSizeError');
      var head = s.slice(0, offset);
      var tail = s.slice(offset);
      this.data = head;
      var newTextNode = this.ownerDocument.createTextNode(tail);
      if (this.parentNode)
        this.parentNode.insertBefore(newTextNode, this.nextSibling);
      return newTextNode;
```

to split the text node and preserve the range, the implemenetation needs to call the browser splitText and then do what it needs to do after. Something like. 

``` javascript
      var replacementNode = wrap(unwrap(this).splitText(offset));
      var parentNode = this.parentNode;
      if (parentNode && parentNode.childrenMightHaveChanged_) {
        parentNode.childrenMightHaveChanged_();
      }
```

Note: Node.childrenMightHaveChanged_  does not exist in the current webcomponents code yet.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!

**Comment by gustavshf** [comment]
We are experiencing this with webcomponentsjs in the Edge browser. :(
