### ISSUE TITLE
upper/lower bound encapsulation for shadow CSS

### ISSUE THREAD

**Issue by johnmave126** [webcomponents/webcomponentsjs#315]
Recently my colleague and I am working on a project using webcomponents.js. We found that the upper/lower bound encapsulation for shadow CSS is not implemented as stated on https://github.com/webcomponents/webcomponentsjs/blob/master/src/ShadowCSS/ShadowCSS.js#L84-91
My colleague comes up an idea as follows:
For each name scope like `x-foo`, we generate a unique name for it, such as `__x_foo_css_helper`, or some other random string.
Then for each selector defined under `x-foo`, we shim the CSS rule from

``` CSS
selector {
    /* some rules */
}
```

to

``` CSS
selector.__x_foo_css_helper {
    /* some rules */
}
```

The position of added string may vary depending on the selector, for a chain of selectors, we add string for each one. If we encounter shadowDOM, we stop and do conventional shimming. 
Which means, we enforce an appended class name to make the class name under this scope unique in global sense.

Then, in template, we add `__x_foo_css_helper` as class for each element. 

For the project we are working on, this trick works. I wonder whether it is a practical and correct way to implement upper/lower bound encapsulation. I am also wondering whether this technique could be added to webcomponentjs.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
