### ISSUE TITLE
Firefox and Firebug weirdness

### ISSUE THREAD

**Issue by ghost** [webcomponents/webcomponentsjs#323]
If I include webcomponents.min.js, in a sample, and have Firebug open, then refreshing the page takes over 10 seconds. If I close Firebug, it still takes 10 seconds. If I never open Firebug, the page refreshes basically instantly.
If I include HTMLImports.min.js this issue does not occur.
It does not occur with Chrome.

If I disable then page refreshes immediately. If I re-enable Firebug, the page still refreshes immediately. This is probably a Firebug issue, but I've never seen this behaviour except when I include webcomponents.min.js.

**Comment by jmesserly** [comment]
Just a guess: webcomponents.js includes ShadowDOM polyfill. This is not included in HTMLImports.js, or in webcomponents-lite.js. It also won't be used in Chrome (which has native ShadowDOM).

SD Polyfill wraps every DOM object. It's not unusual to see 10x slower performance on Firefox for DOM creation benchmarks.

I don't recall how Firebug is architected, but if it runs in the context of the page, it will be slowed down a lot by the presence of the polyfill.

A few ways to test this theory:
* Use webcomponents-lite.js, do things get much faster?
* In Chrome, force ShadowDOM polyfill via: `<script src="path/to/webcomponents.min.js" shadow></script>` (I think "shadow" is enough to force it in Chrome ... you can double check at the console that `window.ShadowDOMPolyfill` is present, and `document.body !== document.querySelector('body')`. Do things get much slower?

**Comment by back5576** [comment]
I changed to webcomponents-lite.js

This drops the page refresh time (when Firebug window is displayed) from 10+ seconds to about 2 seconds.
It still adds a noticeable delay to rendering. Without showing Firebug, rendering is near-instant.
And this delay is still present after Firebug window is closed.

Adding "shadow" to Chrome did not add window.ShadowDOMPolyfill or make document.body !== document.querySelector('body')
And render speed was unchanged (is instant)
Adding "shadow" made Firefox unusable. Got "not responding" message when refreshing test page. It did eventually render - in about 15-20 seconds.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
