### ISSUE TITLE
The following code doesn't show properly in IE 11 and Firefox 38

### ISSUE THREAD

**Issue by lygstate** [webcomponents/webcomponentsjs#330]
```
<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.7.3/webcomponents.js"> </script>
  </head>
  <body>
    <div>
      <h3>Light DOM</h3>
      <section>
        <div>I'm not underlined</div>
        <p>I'm underlined in Shadow DOM!</p>
      </section>
    </div>

    <script>
    var div = document.querySelector('div');
    var root = div.createShadowRoot();
    root.innerHTML = '\
        <style>\
          h3 { color: red; }\
          content[select="h3"]::content > h3 {\
            color: green;\
          }\
          ::content section p {\
            text-decoration: underline;\
          }\
        </style>\
        <h3>Shadow DOM</h3>\
        <content select="h3"></content>\
        <content select="section"></content>';
    </script>
  </body>
</html>

```

**Comment by jmesserly** [comment]
just a guess: ShadowDOM polyfill doesn't handle styles on its own. That's covered by ShadowCSS:
https://github.com/webcomponents/webcomponentsjs/blob/master/src/ShadowCSS/ShadowCSS.js

ShadowCSS needs some help though--it doesn't kick in automatically. You'll want to start with ShadowCSS.shimStyling.

**Comment by lygstate** [comment]
What's ShadowCSS.shim ? Should I include it directly?

**Comment by jmesserly** [comment]
ShadowCSS is included in webcomponents.js already. I linked to it above. The file is pretty readable, maybe have a look and see if it will work for you. Wish I could give more help, but I'm not very familiar with that code.

Perhaps the test cases provide some ideas on how to use it: https://github.com/webcomponents/webcomponentsjs/tree/master/tests/ShadowCSS/html

It's designed to work well with Custom Elements, which are the most common use case right now for Shadow DOM.

**Comment by addyosmani** [comment]
@lygstate were you able to get ShadowCSS working for your use case?

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
