### ISSUE TITLE
Shadow DOM fails throws 'Assertion failed' when removing script elements

### ISSUE THREAD

**Issue by Smudge3806** [webcomponents/webcomponentsjs#331]
Hi,

My applications dependency manager (stealjs) removes script elements from the document head after a script is loaded to prevent memory leaks and other magic. The Shadow DOM polyfil in v0.7.3 seems to not like this.

Any thoughts?

Thanks

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
