### ISSUE TITLE
Shadow DOM doesn't work inside foreignObject element of SVG on browsers other than Google Chrome

### ISSUE THREAD

**Issue by Saneyan** [webcomponents/webcomponentsjs#338]
I try to use Shadow DOM inside foreignObject of SVG, but browsers other than Google Chrome don't work Shadow DOM well.

Here is a part of HTML:

``` html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="1920" height="1080" viewBox="0 0 1920 1080">
  <line x1="100" y1="250" x2="500" y2="250" style="stroke:rgb(255,0,0);stroke-width:2">
  <foreignObject>
    <object-label></object-label>
    <object-label style="left: 500px"></object-label>
  </foreignObject>
</svg>
```

The `object-label` is a custom element which is registered by Polymer. Of course, the custom element works outside SVG (not inside foreginObject).

Is this bug?
Thanks.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
