### ISSUE TITLE
webcomponents.js causes entire website redirected results in 404 on Safari

### ISSUE THREAD

**Issue by agektmr** [webcomponents/webcomponentsjs#345]
My [blog](https://blog.agektmr.com/) recently employed Polymer1.0 with webcomponents-lite.min.js. While it works without any problem on Chrome or Firefox, Safari behaves weirdly showing 404 page. FWIW, this website is using SSL on Cloudflare.
1. First access to [the site](https://blog.agektmr.com/) works usually fine.
2. Clicking on any links will cause redirected to weird URL `https://blog.agektmr.com/^[%20/t/r/n/f]+|[%20/t/r/n/f]+$/g`.
3. After the incident, accessing to any page of this website will end up redirected to the same URL with 404 until you reboot Safari.

By scanning through webcomponents.js code, I found a code that significantly resembles with the URL above.

https://github.com/webcomponents/webcomponentsjs/blob/master/src/URL/URL.js#L473

I highly doubt webcomponents.js is causing this behaviour. Do you have any idea?

**Comment by rahul-vs** [comment]
Did you solved this issue? I am facing similar issue.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
