### ISSUE TITLE
onload event.target.import is undefined in Firefox

### ISSUE THREAD

**Issue by zakm** [webcomponents/webcomponentsjs#346]
In Chrome (43.0.2357.132), the following code logs the contents of whatever is in component.html.
In Firefox (41.0a2), it logs `undefined`. 
I could be mistaken, but I feel like `event.target` should be equal to `document.querySelector('link[rel="import"]')` (for which `.import` is defined) in this context.

``` html
<!doctype html>
<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.7.6/webcomponents.min.js"></script>
    <script>
      function imp(event) {
        console.log( event.target.import );
      }
    </script>
    <link rel="import" href="component.html" onload="imp(event)">
  </head>
</html>
```

**Comment by thorinisme** [comment]
i meet the same issue.

Here is the solution:

```js
function imp(event) {
        console.log( document.querySelector('link[rel=import][href="'+event.target.getAttribute('href')+'"]').import );
}
```

because event.target is a wrapper object. It's not the HTMLLinkElement. It's more like a proxy. The wrapper doesn't implement "import" property. So you have to first find the real element.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
