### ISSUE TITLE
Unable to get property '__wrapper8e3dd93a60__' of undefined or null reference

### ISSUE THREAD

**Issue by pironim** [webcomponents/webcomponentsjs#350]
I get this error from time to time on IE11 on page reload.
Unable to get property '**wrapper8e3dd93a60**' of undefined or null reference
Here is screenshot:
http://joxi.ru/1A5QqZzuPd0nAE

and stacktrace http://joxi.ru/823nNLkSBv6YmO

I use :
  "polymer": "Polymer/polymer#0.5.6",
  "webcomponentsjs": "webcomponents/webcomponentsjs#0.6.1",

trying with 0.7.6 web components with no luck.
I have a latest win8.1 IE11 with all updates. - official vmWare image from microsoft site.

what I'm doing wrong?

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
