### ISSUE TITLE
Investigate HTMLImports polyfill on Windows 8.1 Cordova

### ISSUE THREAD

**Issue by kevinpschaaf** [webcomponents/webcomponentsjs#364]
Report here https://github.com/Polymer/polymer/issues/2168 indicates Polymer fails to run on Windows 8.1 Cordova.

Could possibly be an issue with XHR to local filesystem in that environment.

**Comment by Prontsevich** [comment]
Hi, there were no any errors in the console. And actually I tried to start Windows 8.1 app for desktop, not mobile. But it's the same behavior as for desktop and also as for mobile, there are no any errors in console and no any content in controls.

**Comment by chimon2000** [comment]
Ran into this same issue on Windows 10. Was able to get more information by debugging in Visual Studio:

````
Unhandled exception at line 10, column 21807 in ms-appx://io.cordova.myapp35698d/www/bower_components/webcomponentsjs/webcomponents-lite.min.js

0x800c001c - JavaScript runtime error: Unable to add dynamic content. A script attempted to inject dynamic content, or elements previously modified dynamically, that might be unsafe. 
For example, using the innerHTML property to add script or malformed HTML will generate this exception. 
Use the toStaticHTML method to filter dynamic content, or explicitly create elements and attributes with a method such as createElement.  
For more information, see http://go.microsoft.com/fwlink/?LinkID=247104.
````

**Comment by chimon2000** [comment]
Unminified version breaks at

`Unhandled exception at line 1377, column 7 in ms-appx://io.cordova.myapp35698d/www/bower_components/webcomponentsjs/webcomponents-lite.js`

**Comment by garlicnation** [comment]
It looks like we need to wrap our insertNode in MSApp.execUnsafeLocalFunction if it's available.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
