### ISSUE TITLE
Custom Element Polyfill Lifecycle better than native Chrome?

### ISSUE THREAD

**Issue by noopole** [webcomponents/webcomponentsjs#378]
If I define a component in a closure executed at creation, the attachedCallback is never called by Chrome native implementation, while it's handled perfectly by the polyfill on IE and Firefox.
In Chrome I'm forced to link manually the prototype attachedCallback to its "closed" counterpart.

Who's right? I think the polyfill behaviour is better (more intuitive with less coding).

**Comment by jmesserly** [comment]
hi @noopole, could you attach some example code showing the behavior you got and the behavior you expected. http://jsbin.com/?html,output is good for this

**Comment by noopole** [comment]
Here is an exemple : http://jsbin.com/panajawavo/1/edit?html,output

Without the 4 lines under  '//Native hack', the attachedCallback won't be called on Chrome, but still works with polyfilled.

NB: I use another polyfill because I don't know your CDN but it perfomed as well locally.

**Comment by jmesserly** [comment]
ah, gotcha. Yeah adding attachedCallback to the instance like that doesn't work. I believe the native implementation doesn't see it on registerElement call, so concludes it's not there. The polyfill is simpler/more permissive in this regard, it doesn't try and call it until later.

but yes, it looks like native behavior is correct:
`13. Transfer callback named attachedCallback to LIFECYCLE from property named attachedCallback on PROTOTYPE` in http://w3c.github.io/webcomponents/spec/custom/#registering-custom-elements

whether we could duplicate that in the polyfill, I'm not sure, but probably we could. We'd just use something like `Object.getOwnPropertyDescriptor(customElem, 'attachedCallback')` instead of `customElem.attachedCallback` to get it.

here's a version that works http://jsbin.com/hinufekuco/edit?html,console,output

**Comment by noopole** [comment]
Thank you for your explanations. 
In my opinion the polyfill is better because it won't break the dynamic nature of javascript function call.

But there are probably good reasons for *isolating* the "LIFECYCLE" callbacks. (I also tried to link my intenal function to `this.__proto__.attachedCallback` but with not more success.)

Anyway I'll look at other vendor implementations to know their own interpretation of the specs.

Here is a new JSBin that take advantage of closures at creation time and work for any browser.
http://jsbin.com/defexecoqu/1/edit?js
