### ISSUE TITLE
HTML Imports + iOS 7 + templates not working

### ISSUE THREAD

**Issue by nomego** [webcomponents/webcomponentsjs#382]
When trying to use HTML Imports to import templates (in Polymer), it fails in iOS 7 but works in Firefox, Chrome and iOS 8.

Not sure exactly where this i happening but importing a template like https://gist.githubusercontent.com/nomego/515a3681142c8d0d14f1/raw/106f90338652730860f3e0ed50d0964ba60232c5/template.html will cause the HTML import content `template` tag (`link.import.querySelector('template')`) to have it's inner content wiped (`<template is="dom-bind"></template>`).

However, `link.__resource` from the polyfill contains the whole contents of the imported file, so a workaround I'm using right now is to check if `template.innerHTML === ''` (which it never is on Firefox or Chrome) and if so import `link.__resource`.

I've tried a few ways to do this, but landed on 

``` js
var div = document.createElement('div');
div.innerHTML = link.__resource;
var t = div.querySelector('template');
appendTo.appendChild(t);
```

Example JSBin with workaround for iOS 7 at: http://jsbin.com/zalegepudi/edit?html,console,output
Related to polymer/polymer#2157

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
