### ISSUE TITLE
node.ownerDocument.createElement results in wrong initial prototype

### ISSUE THREAD

**Issue by sparhami** [webcomponents/webcomponentsjs#383]
If you create a custom element through an Element's `.ownerDocument`, it will not initially have the correct prototype.

This makes it hard to reason about elements as functions that might be expected to exist on the prototype chain will not be there. Adding the Element to the DOM and waiting results in it being upgraded. If the Element is never attached to the DOM, it will never be upgraded. 

Reproduced in: https://github.com/sparhami/webcomponentsjs_createElement/blob/master/index.html

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
