### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by krampstudio** [webcomponents/webcomponentsjs#397]
Could you please publish the lastests versions on npm ? The last one is 0.7.2 https://www.npmjs.com/package/webcomponents.js but a lot of progress has been made since.

Keep being awesome!

**Comment by kapouer** [comment]
:+1: @azakus ?

**Comment by addyosmani** [comment]
I'll take care of updating, but would be great to get publishing to npm in as part of our official release pipeline :cat:

**Comment by addyosmani** [comment]
`npm install webcomponents.js@0.7.18` will get you the latest version. 

It looks like at some point, we accidentally git tagged a `0.7.2` here (later re-tagged) that was published to npm. Imo, we should aim to realign with the version numbering here once wc.js hits `0.7.3`, unless there are other thoughts on this.

**Comment by kapouer** [comment]
0.7.2 < 0.7.3 < 0.7.18

**Comment by AndreasGalster** [comment]
Any timeline for this? Also, how will this be working in the future? It seems that some of the polyfills create script tags, whereas I saw entrypoints is using imports. Will there be a version which just relies on imports, so that bundling will work as expected in tools such as webpack or meteor?

**Comment by codecholeric** [comment]
This is kind of confusing, since one wouldn't expect the npm version to be behind so much. Did cost me some time, until I realized, that the features I wanted weren't implemented, because the npm version is hopelessly outdated... It would almost be better to have no npm version, than to have one that's so far behind.

**Comment by 4esnog** [comment]
@codecholeric Are you using this package?
https://www.npmjs.com/package/@webcomponents/webcomponentsjs
As far as I know, now this is the right and maintainable one.

**Comment by codecholeric** [comment]
Oh, you're right, looks good :smiley: 
I was looking at https://www.npmjs.com/package/webcomponents.js-v1 and https://www.npmjs.com/package/webcomponentsjs, which are the only npm packages Google pulls up on the first result page, when I search for 'npm webcomponentsjs' :frowning_face: 
Anyway, that's cool, because now I can throw Bower out of my build again, thanks a lot!!

**Comment by codecholeric** [comment]
Is this because I'm a Node noob, or is it really so hard to find this Package? I was just double checking, but Google > 'npm webcomponentsjs' really doesn't pull up the correct package at all on the first 5 pages, and even when I search directly via the npm web search, the package is on page 2.
Too bad, that it's so much easier (at least in my case), to find outdated or strange stuff (the second package doesn't seem to have any origin linked and the license is different??).
Don't know if that is bad practice, but wouldn't it be possible to mention the latest bower and npm package on Github at least? For example within "How to use"?
Actually the Bower package is mentioned on the website https://www.webcomponents.org/polyfills/, so I had no trouble finding that, just the npm package...

**Comment by AndreasGalster** [comment]
The webcomponents package is fairly new and only recently got updated to an up-to-date version. I'm guessing as more people adopt the package, it'll grow in popularity and search engines will rank it higher.

**Comment by 4esnog** [comment]
There are already two PR with instructions updates:
https://github.com/webcomponents/webcomponentsjs/pull/783
and https://github.com/webcomponents/webcomponentsjs/pull/791
Hope it will be merged really soon :)

**Comment by codecholeric** [comment]
+1 for #783 mentioning `npm install @webcomponents/webcomponentsjs` :wink: 
Would definitely have saved me some time...

**Comment by TimvdLippe** [comment]
The polyfills are now published on https://www.npmjs.com/package/@webcomponents/webcomponentsjs
