### ISSUE TITLE
webcomponents.min.js does not work in IE10

### ISSUE THREAD

**Issue by williamcodes** [webcomponents/webcomponentsjs#403]
We've seen the same issue with webcomponents-lite and with IE11 on our own app, however here's an example of the problem on the polymer website. Any thoughts on what might be causing it? 

https://elements.polymer-project.org/elements/iron-a11y-announcer?view=demo:demo/index.html

```
SCRIPT16386: No such interface supported
webcomponents.min.js, line 11 character 1388
```

**Comment by williamcodes** [comment]
I ran it again on my own app and it's returning this very similar error that seems to be coming from a related place in the code.
```
SCRIPT3: Member not found

webcomponents-lite.js: line 2176 character 7
```

**Comment by jmesserly** [comment]
maybe try with an unminified version and see what the stack trace looks like and where it's failing? it's hard to know from those error messages.

**Comment by jmesserly** [comment]
also you mentioned IE10 in the title but IE11 in the first message...?

**Comment by kaldrenon** [comment]
@jmesserly - I'm pairing with William on this issue.

We're seeing this issue in both IE10 *and* IE11, and William's [added comment](https://github.com/webcomponents/webcomponentsjs/issues/403#issuecomment-142680223) is from the un-minified version of `webcomponents-lite.js` loaded in our app.

This seems to trace back to a call in our code to `document.createElement`

**Comment by kaldrenon** [comment]
Here is a screenshot of part of the stacktrace - we aren't able to copy and paste the stack trace because we're using IE10 on a VM and the clipboard isn't working.

http://i.imgur.com/9Bqkc7l.png

**Comment by williamcodes** [comment]
@jmesserly the demo page I linked to is not working in IE10. I have not confirmed it in IE11 but I think it will be broken there as well because in our app it is broken for both.

**Comment by williamcodes** [comment]
@jmesserly I can't switch to an unminified version because there are no sourcemaps and it's the polymer team's demo page: https://elements.polymer-project.org/elements/iron-a11y-announcer?view=demo:demo/index.html

I would send code from my client's project but it's closed source. Any polymer team people want to see why their demo page isn't working in IE?

**Comment by jmesserly** [comment]
thanks for those additional details! 

Just a guess, it might be an issue with https://github.com/PolymerElements/iron-a11y-announcer, unless you see it on other elements? CC @cdata and @tjsavage who worked on it (I'm guessing based on commits).

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
