### ISSUE TITLE
Example does not work in Firefox or IE11, but it works fine in Chrome

### ISSUE THREAD

**Issue by Meai1** [webcomponents/webcomponentsjs#406]
**Summary:**
The attached test succeeds in Chrome but fails in Firefox 40 and IE11.
What is also wierd: It succeeds "sometimes"(!?) when stepping through with the Firefox debugger.
It never succeeds in IE11.
I cannot explain this, I'm using raw HTML5 apis!

**Resources:**
Find the sample code here: https://goo.gl/kXcrvq

**Reproduction:**
Simply browse to "test/b-dialog-test.html" via a local webserver and Chrome(works) and Firefox(does not work).

Please help!

**Comment by flawyte** [comment]
I've made a website using this library too, and it doesn't work on Firefox 43. Unknown error (nothing is printed out in the console except a red cross showing the error).

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
