### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'n')

### ISSUE THREAD

**Issue by oathcomrade** [webcomponents/webcomponentsjs#408]
I am getting this error message on line 626 in Safari 9.0 when I use the minified version. Not sure where the bug is coming from.
![bildschirmfoto 2015-10-06 um 22 57 36](https://cloud.githubusercontent.com/assets/10003180/10322379/af781b28-6c7d-11e5-8a8f-bdc2fe58aff9.png)

**Comment by azakus** [comment]
Can you try with the unminified version?

**Comment by oathcomrade** [comment]
Yes, no error there...

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
