### ISSUE TITLE
Mouse events not redirected with <label for="id"> tags

### ISSUE THREAD

**Issue by indolering** [webcomponents/webcomponentsjs#410]
Clicking on a `<label for="id">click here</label>` should redirect the pointer focus to the element with the ID declared in the `<label>`'s `for` attribute, typically an input tag.  Currently, the Shadow DOM polyfill redirects focus to the first element with a matching ID.  [This JSBin example](http://jsbin.com/haqumal/3/edit?html,output) works on Chrome but it doesn't work on Firefox.

```
<!doctype html>
...
<body>
    <x-example></x-example>
    <x-example></x-example>

<dom-module id="x-example">

  <template>
    <input id="test" />
    <label for="test">Clicking here should redirect pointer focus to the input on my left.</label>
  </template>
  <script>
      Polymer({
        is: "x-example"
      });
  </script>
</dom-module>
</body>
```

![image](https://cloud.githubusercontent.com/assets/44454/10349099/02727bf8-6cfa-11e5-881d-9b65e02c402b.png)

**Comment by indolering** [comment]
Can I at least get a priority label on this bug?

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
