### ISSUE TITLE
Event dispatched from Shadow DOM polyfill throws exception with jQuery UI

### ISSUE THREAD

**Issue by martinsik** [webcomponents/webcomponentsjs#418]
If you run this example [https://jsfiddle.net/6d5dy417/1/](https://jsfiddle.net/6d5dy417/1/) that just includes jQuery 2.1.4, jQuery UI 1.11.4 and ShadowDOM 0.7.15 and try to drag the red square it throws an exception:

`Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.`

I'm using Chrome 46, also if you remove the `<script>` tag with the polyfill it works fine. I'm not even using any of the Shadow DOM's methods in the example.

Exception thrown:

![screen shot 2015-10-20 at 11 35 30](https://cloud.githubusercontent.com/assets/238765/10603527/b8205960-771e-11e5-997b-8bab0ac04e56.png)

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
