### ISSUE TITLE
CustomElements.upgradeAll throws when cloneNode'ing trees that include textNodes

### ISSUE THREAD

**Issue by kevinpschaaf** [webcomponents/webcomponentsjs#443]
This [change](https://github.com/webcomponents/webcomponentsjs/pull/439/files#diff-1883af06f66c8c928d72352cd1c8e0b4R309) inadvertently caused an issue with the `cloneNode` implementation when running on the Template polyfill, when `upgradeAll` tries to Template "bootstrap" textNodes coming through `cloneNode` due to lack of a `querySelectorAll` API.

Although it could be avoided by `upgradeAll` or `bootstrap` testing for node types that have `querySelectorAll`, a closer look at that change also pointed out that it effectively adds a `querySelectorAll` to every node being stamped via `importNode` which is a potential performance concern.  As such, we should consider reverting that change and solving the issue in another way.  There are alternative approaches in Polymer being considered that would eliminate the original need for this change.

**Comment by azakus** [comment]
I'd like to have the alternative ready to go before we revert #439.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
