### ISSUE TITLE
webcomponentsjs not working in private window with Safari and iOS Safari

### ISSUE THREAD

**Issue by pensierinmusica** [webcomponents/webcomponentsjs#455]
Hi,

I'm using `webcomponentsjs` (v. 0.7.18) for a Polymer project.

It all works fine, but when I open my app in a new "private window" in Safari (v 9.0.1) or iOS Safari (v 9.1) I get this error:

> QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota. – webcomponents.min.js:11:13385

Any idea about what is causing this issue, and how it can be fixed?

Thanks, cheers!

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
