### ISSUE TITLE
simple example fails on firefox

### ISSUE THREAD

**Issue by John-Colvin** [webcomponents/webcomponentsjs#456]
See http://jsbin.com/picenureru/1/edit?html,console,output for the example, it works on chrome (kindof, see https://stackoverflow.com/questions/34026007/instantiating-custom-element-by-adding-is-attribute-doesnt-trigger-createdcal) but on firefox it breaks with the error `TypeError: 'innerHTML' setter called on an object that does not implement interface Element.`

**Comment by John-Colvin** [comment]
the same error occurs on Safari.
OS X 10.11.2 Beta (15C48a), Firefox 42.0, Safari 9.0.2 (11601.3.9), Chrome 46.0.2490.86 (64-bit)

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
