### ISSUE TITLE
:host selector does not work in IE11

### ISSUE THREAD

**Issue by tomalec** [webcomponents/webcomponentsjs#458]
Here is an example http://jsbin.com/doquke/edit?html,console,output
Even `polyfill-next-selector` does not help.

``` html
<template id="my-templ">
    <style>
        polyfill-next-selector {
            content: ':host';
        }

        :host {
            color: green;
            background: lightgreen;
        }
    </style>

    <content></content>
</template>

<div id="my-element">
    I'm green
</div>
<script>
    var el = document.getElementById('my-element');
    var template = document.querySelector("#my-templ");
    var clone = document.importNode(template.content, true);
    el.createShadowRoot().appendChild(clone);
</script>
```

**Comment by zoechi** [comment]
Looks like Polymer/polymer#2701

try `:host ::content {`

**Comment by tomalec** [comment]
After reading tests I have figured out that `WebComponents.ShadowCSS.shimStyling` helps http://jsbin.com/ribilev/2/edit?html,console,output
For my case it's not that bad as I use it for custom element, but in general doing so for all `div`s is quite weird.

Plus, it would be nice to document it somewhere.

**Comment by koenkivits** [comment]
As it happens I literally just started writing some documentation on this because of #451. It's taking me a while due to a lack of spare time, but it is being worked on.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
