### ISSUE TITLE
(Angular 2.0.0 beta.0 + Polymer 1.0) paper-input data binding not working on IE11

### ISSUE THREAD

**Issue by ldtung** [webcomponents/webcomponentsjs#471]
I have a paper-input component declared as below, where myField is a field initialized with value="TestValue"

paper-input ngDefaultControl [(ngModel)]="myField" label="my label"

On chrome, it's working fine, "TestValue" is displayed when loading screen.
The two way data binding working fine.
but on IE11, "TestValue" is not displayed. Even if i changed value in paper-input to something else,
the data model is not updated.

I debugged into the code, and see that NG2 has already updated the paper-input's value to "TestValue" when rendering the screen but seems the input inside does not see the same value

Any idea?

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
