### ISSUE TITLE
IE11 can't reload webcomponents.js on a framed page (v0.7.20)

### ISSUE THREAD

**Issue by elvisqi** [webcomponents/webcomponentsjs#478]
I'm able to reproduce the same issue above using the release v0.7.20
- Please using IE11 access this link http://res.wisedu.com/FE/ie11/frmPage.html
- Open the browser console and then click on Reload frame button and observe an exception on the same spot described above.

**Comment by elvisqi** [comment]
ie9 & ie10 & edge is fine

**Comment by garlicnation** [comment]
@elvisqi: This is behind http authentication for me. Can you provide a publicly-accessible link?

**Comment by elvisqi** [comment]
http://res.wisedu.com/FS/ie11/frmPage.html

SCRIPT5007
webcomponents-lite.js (971,7)

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
