### ISSUE TITLE
webcomponents.js breaks jQuery Mobile

### ISSUE THREAD

**Issue by SunboX** [webcomponents/webcomponentsjs#49]
If I include webcomponents.js in any jQuery Mobile page and try to navigate, I get:

**jquery.mobile-1.4.5.js:5671**
`TypeError: this.window[0] is undefined`

**Demo:**

http://jsbin.com/fohimohupa/2/edit?html,js,output

How can I fix this?

![window length 0](https://cloud.githubusercontent.com/assets/83344/5029988/449f778e-6b4c-11e4-9fd7-651ad4a8b35f.png)

**Comment by JEAxero** [comment]
Just wondering if you happen to know if this same problem occurs with webcomponents-lite.js (that only includes Custom Element and HTML Template support and excludes the Shadow DOM)? (references: http://webcomponents.org/polyfills/ and https://github.com/WebComponents/webcomponentsjs)

**Comment by jmesserly** [comment]
yeah, unfortunately ShadowDOM polyfill cannot wrap certain properties like `document` ... so those should be used as `ShadowDOMPolyfill.wrap(document)`. Perhaps this solution will work?
https://github.com/webcomponents/webcomponentsjs/issues/89#issuecomment-65960193

**Comment by jmesserly** [comment]
cc @robdodson who has familiarity of working around the `document` issue

**Comment by JEAxero** [comment]
>>> unfortunately ShadowDOM polyfill

But webcomponents-lite.js excludes the Shadow DOM part of the polyfill. So, I'm wondering (and am hoping) that, perhaps excluding that will let me use just the Custom Element and HTML Import features. I'll try to quickly test it myself but am asking if anyone else has tried this since webcomponents-lite.js seems to be a relatively new thing at webcomponents.org

**Comment by jmesserly** [comment]
Ah great point @JEAxero ... using webcomponents-lite.js most likely avoids the bug. Yeah, I'm curious too. Do report back and let us know how the experiment goes :). If the bug still happens, that's good to know too, means my guess is wrong and it's not SD-poly related.

**Comment by JEAxero** [comment]
A quick update with some good news... I had recently created a skeletal app using Cordova/PhoneGap v4.1.2, jQuery 1.11.2, jQuery UI 1.11.2, and jQuery Mobile 1.4.5 (all were the latest released versions as of a few weeks ago).

Today, I augmented that sample app with the latest (v0.5.3) webcomponents-lite.js that excludes the Shadow DOM.

I've just finished testing a very rudimentary Custom Element and a very simple HTML Import in my app's index.html file and they work fine in IE9, IE11, Chrome, and the iPad Simulator! (That's all I've tried.)

One gotcha... HTML Import fails in the iPad Simulator if you use the default Cordova/PhoneGap file handling which loads local files from file:///   but... if I move my import.html file to a known location on the server and make sure that all of the files being imported are accessible with absolute or relative paths that match the server's layout, it works fine. So, the underlying problem seems to be related to importing from file:///

**Comment by jordanmkoncz** [comment]
Just ran into this issue on a project where I'm using Polymer (which depends on the non-lite version of webcomponents.js) along with jQuery Mobile. Fortunately I didn't need jQuery Mobile to change the hash so I was able to get around the issue by essentially stopping jQuery Mobile from executing the code that gets broken by webcomponents.js by doing what SunboX recommended and disabling changeHash in jQuery Mobile.

Would be good to find a fix for this for people who aren't able to get around the issue in this way (e.g. people who need the changeHash functionality of jQuery Mobile).

**Comment by TimvdLippe** [comment]
This appears to be resolved: http://jsbin.com/timuqon/edit?html,js,output
