### ISSUE TITLE
Wrong order of detached, and mutation callbacks execution

### ISSUE THREAD

**Issue by tomalec** [webcomponents/webcomponentsjs#491]
It seems that Mutation Observer callbacks are executed in wrong order, and what is worse in the wrong moment regarding `detachedCallback`.
In FF and IE, If I detach element, then append/remove child element, mutation callback is executed before detached one:

``` js
myEl.parentElement.removeChild(myEl);
myEl.removeChild(myEl.firstElementChild);
```

Then, even tough I `.disconnect`ed observer at `detachedCallback`, mutation callback is executed.

http://jsbin.com/cuqeti/edit?html,console,output

In Chrome it works as expected.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!

**Comment by tomalec** [comment]
Migrated jsbin to V1 http://jsbin.com/tesehinaru/1/edit?html,console,output

Mutation callback and `disconnectedCallback` seems to be aligned now. Thanks!

**Comment by TimvdLippe** [comment]
That was my supicion. Glad to hear @tomalec ! Sorry for not responding sooner and properly closing this issue as soon as we addressed the root problem.
