### ISSUE TITLE
WeakMap polyfill issue on IE 10

### ISSUE THREAD

**Issue by itadakimas** [webcomponents/webcomponentsjs#495]
Hi !

I get the error below on the console in IE 10:

`
SCRIPT5077: Cannot define property '__st596897419180249863__': object is not extensible 
webcomponents.js, line 69 character 65
`

Is it a known issue?

**Comment by azakus** [comment]
Can you provide a JSBin containing a set of reproducible steps?

**Comment by Leeds-eBooks** [comment]
I have just come across this. Really complex setup, so hard to create a repro, but this happens when trying to use `WeakMap.set()`, thereby using the `WeakMap` polyfill bundled with webcomponentsjs.

`__st596897419180249863__` is the random key used to add the `value` object in `WeakMap.set(key, value)` to the `key` object as a sort of "hacky" polyfill for native `WeakMap`.

I think this error occurs when `key` in `WeakMap.set(key, value)` is a non-extensible object (therefore the hacky polyfill can't do its thing). I can't think of a solution to this other than using a completely different `WeakMap` polyfill. However all the `WeakMap` polyfills I've seen use this same approach. As a *really* hacky hotfix, I just did this: `window.WeakMap = window.Map` (**don't** do this unless, like me, you really need a quick fix!!).

Weirdly, however, this happened to me in the Android 4.4.2 WebView, but it does not happen with exactly the same code and setup in the Android 5.0 WebView. This suggests to me that the problem is more subtle than I have explained...

**Comment by Leeds-eBooks** [comment]
Ok so it turns out Android 5 has native `WeakMap` support, Android 4.4 doesn't. This is why I wasn't getting this issue in Android 5 but I was in Android 4.4.

In fact, if you look at the [compatibility table](http://kangax.github.io/compat-table/es6/#test-WeakMap), `"frozen objects as keys"` is listed as a know problem of polyfills.

The solution, which I think should be documented, is never to use frozen objects as keys in `WeakMap`s unless you can be certain that your code will never be run in an environment that needs this polyfill. If, like me, you can't guarantee that (e.g. it's in code outside your control), the hacky workaround I mentioned above still stands, with an added check for native support:

```html
<script>
  window.hasNativeWeakMap = 'WeakMap' in window
</script>

<script src='/components/webcomponents.js'></script>

<script>
  if (!window.hasNativeWeakMap) {
    window.WeakMap = window.Map
  }
</script>
```

**Comment by itadakimas** [comment]
I think the problem is that HTMLElement is frozen on IE 10...

**Comment by Leeds-eBooks** [comment]
@itadakimas Are you actually using `new WeakMap()` in your own code?

**Comment by itadakimas** [comment]
@Leeds-eBooks no, but here is the code example that I use in the project:

```Javascript

(function() {

  ///////////////////////////////////////////////////////////////////////////
  // LOCAL VARIABLES
  ///////////////////////////////////////////////////////////////////////////

  // Get the contents of the template (_currentScript is available with webcomponents.js, use currentScript if you don't use this Polyfill)
  var template = document._currentScript.ownerDocument.querySelector('template');

  // Create a prototype for this component
  var prototype = Object.create(HTMLElement.prototype, {

    ///////////////////////////////////////////////////////////////////////////
    // INSTANCE PROPERTIES
    ///////////////////////////////////////////////////////////////////////////

    // Example property
    firstname: {

      get: function() {

        console.log("firstname getter");
        return this._firstname;
      },
      set: function(firstname) {

        console.log("firstname setter");
        this._firstname = firstname;
        this.shadowRoot.querySelector(".firstname").textContent = firstname;
      }

    },

    ///////////////////////////////////////////////////////////////////////////
    // INSTANCE METHODS
    ///////////////////////////////////////////////////////////////////////////

    // Example method
    sayHello: function() {

      console.log("Hello " + this.firstname);
    }

  });

  ///////////////////////////////////////////////////////////////////////////
  // WEBCOMPONENT INTERFACE
  ///////////////////////////////////////////////////////////////////////////

  // Register a createdCallback
  prototype.createdCallback = function() {

      var clone;

      // Grab the contents of the template
      clone = document.importNode(template.content, true);

      // Add the template contents to the shadow DOM
      this.createShadowRoot().appendChild(clone);

      console.log("example component created");
  };

  // Called when the component instance is attached to the DOM
  prototype.attachedCallback = function() {

    console.log("example component attached");
  };

  // Called when one of this components attributes change
  prototype.attributeChangedCallback = function(attrName, oldVal, newVal) {

    console.log("example component attribute changed");
    console.log("attr = %s, oldValue = %s, newVal = %s", attrName, oldVal, newVal);
    switch(attrName)
    {
      case "firstname":
        this.firstname = newVal;
        break;
      default:
        break;
    }
  };

  ///////////////////////////////////////////////////////////////////////////
  // INITIALIZATION
  ///////////////////////////////////////////////////////////////////////////

  // Register the element with the document
  document.registerElement("example-component", {prototype: prototype});

}());

```
Works fine on IE11 / Firefox / Chrome / Safari, but not on IE 10.

**Comment by Leeds-eBooks** [comment]
I guess somewhere in there you're triggering `WeakMap.prototype.set()`, but no idea where. As I said above, if you need a workaround for this then replacing global `WeakMap` with `Map` does the job.

**Comment by eugef** [comment]
The problem indeed happens when the frozen object is passed as a key.

Core-js library (that is used for example in babel-polyfill) has a workaround for this case:
https://github.com/zloirock/core-js/blob/master/modules/es6.weak-map.js#L39

I think it make sense to do the same for webcomponents implementation.

**Comment by gregorymachon** [comment]
I had the same issue with Chrome/Chromium v31 (WeakMap is supported natively from v36).

Adding the solution from https://stackoverflow.com/a/35170266/558517 worked for me (storing the value "elsewhere", not on the non-extensible objects), just make sure to include it before webcomponents-lite.min.js. With UglifyJS 3 it takes ~1KB.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
