### ISSUE TITLE
link.import.readyState stays at "loading" on webkit

### ISSUE THREAD

**Issue by kapouer** [webcomponents/webcomponentsjs#499]
I noticed

```
var link = document.createElement("link");
link.rel = "import";
link.href = "/mycomponent.html";
link.addEventListener("load", function() {
  console.log("link readyState", link.import.readyState);
});
document.head.appendChild(link);
```

prints "complete" on firefox and "loading" on epiphany 3.18 / webkitgtk 2.10.7.
There is a high chance it does too on Safari.

UserAgent
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Debian/buildd-unstable (3.18.4-1) Epiphany/3.18.4

**Comment by zanona** [comment]
hey @kapouer, by any change did you have any luck with this?
Apparently when having nested links being loaded inside another component, the load event fires before other imports finished loading and as you said, it is fired at 'loading' instead?

**Comment by kapouer** [comment]
I'm using some kind of workaround here:
https://github.com/kapouer/window-page/blob/master/index.js#L290
but i don't remember so well how it works exactly right now.

**Comment by zanona** [comment]
Thanks @kapouer I will have a look! 👍

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
