### ISSUE TITLE
Can't utilize createDocument() on IE11 and Firefox.

### ISSUE THREAD

**Issue by cpboyd** [webcomponents/webcomponentsjs#508]
I've created a site utilizing Polymer elements with GWT that can generate XML files (as I'd initially reported this issue with GWT https://github.com/gwtproject/gwt/issues/9295)

I ultimately traced the issue back to ShadowDOM overriding the default `document.implementation.createDocument()` functionality which GWT utilizes for generating XML documents via `XMLParser.createDocument()`.

Is there a way that I can retain the default implementation of `createDocument()` and still have compatibility with Polymer?

**Comment by cpboyd** [comment]
To clarify, the issue is more that the new Document object (with Shadow DOM) doesn't implement createProcessingInstruction and isn't compatible with XMLSerializer.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
