### ISSUE TITLE
Angular 1.x and webcomponents polyfill (ng-switch and ng-repeat-start) 

### ISSUE THREAD

**Issue by FMRb** [webcomponents/webcomponentsjs#510]
Hi,
I found some issues working with Angular 1.x and webcomponents. (angular 1.3, 1.4, 1.5, webcomponents 0.7.21)
The issues happen at runtime, when using the angular directives ng-switch and ng-repeat-start, and are isolated to browsers using the polyfill (works fine in chrome).
A quick look at these two angular directives, has lead me to the $animate.enter method, which at some point is doing DOM manipulation.

I have included two pens with the failing examples
Codepens:
- [ng-repeat-start example](http://codepen.io/FMRb/pen/jqVLPQ/?editors=1111)
- [ng-switch exmaple](http://codepen.io/FMRb/pen/dMOVOj/?editors=1111)

I am interested in contributing to fix this issue.

**Comment by cary-smith** [comment]
Related: https://github.com/webcomponents/shadydom/issues/182

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
