### ISSUE TITLE
The createdCallback is fired too late in the CustomElements polyfill

### ISSUE THREAD

**Issue by patrickmatte** [webcomponents/webcomponentsjs#511]
The createdCallback should fire on custom elements immediately after setting element.innerHTML. I guess it is fired later because you are watching for new elements that are added to the body but that is causing a serious bug when you want to call functions or set properties on custom elements immediately after innerHTML.

I think this polyfill should provide some kind of method called "CustomElements.setInnerHTML(element, text)" or something like that so that the polyfill can run through the new elements and instantiate them immediately without waiting until they are added to the body of the document. If the browser actually supports custom elements, then this method would do nothing else then set innerHTML on the specified element.

Does that make sense?

**Comment by patrickmatte** [comment]
I found out that I can force the upgrade of my new elements by calling CustomElements.takeRecords() immediately after calling innerHTML, if the elements are in the DOM. So I'll close the issue.

**Comment by richardjr** [comment]
I found my way to this solution having a similar issue and while the above fix does indeed solve my issues doing a CustomElements.takeRecords() every time your call innerHTML is IMHOP not a fix.

Given the pollyfill is attempting to emulate the native functionality of custom elements, that being that the event createdCallback is fired when the element is in fact created.

The following example being a point in case:

for (var i=0;i<loop_data.length;i++) {
.......
 $(target).append($(template).html());
}

If the template contains data on custom elements that are state dependent to the loop then with native support in chrome it well render correctly. However in the pollyfill the templates will be picked up later and all executed in one go.

To fix this currently I have to do:

for (var i=0;i<loop_data.length;i++) {
.......
 $(target).append($(template).html());
 CustomElements.takeRecords()
}

I would propose that the innerHTML override should in fact perform this step for us?

**Comment by richardjr** [comment]
Just noticed this issue is closed any chance this issue can be re-opened rather than me making a new issue?

**Comment by patrickmatte** [comment]
I read somewhere that you could also use CustomElements.upgrade(element); but that hasn't been working for me in Safari and Firefox so I resolved to using CustomElements.takeRecords. It would be much better if CustomElements.upgrade actually worked. CustomElements.takeRecords requires that you add the element to the document otherwise it won't work. That is not ideal if the parent element that you used to set innerHTML is not in the DOM. And I suppose that takeRecords must recursively runs through the DOM to find all the new elements so it must be a large processing overhead if you create a lot of items and need to call takeRecords every time.

**Comment by richardjr** [comment]
I haven't looked at the code yet but I suspect you are correct in your assumption that takeRecords will do a full DOM scan as I see no other way to detect changes as I have faced similar issues before and this always ends up being the solution as horrible as it seems.

I suspect the reason for doing timed updates to check for new elements is done specifically to avoid said processing but then we are back to the problem of it not working as per the browsers that don't require the pollyfill.

I will take a look at the code and am happy to work a pull request if there can be an agreement on how this might be solved. For those of us that need the instant update maybe it can be done as an optional setting?

**Comment by patrickmatte** [comment]
Have a look at this thread
https://groups.google.com/forum/#!topic/polymer-dev/Df55skoYYNE
It says that you can call CustomElements.upgrade(element)
I don't know if this upgrade method was working at some point in time but it is not working as such with the current code base.
Let me know if you find anything.

**Comment by patrickmatte** [comment]
After digging a bit more into this, I found that calling CustomElement.upgradeAll(element) or CustomElement.upgradeSubtree(element) worked like expected. I guess CustomElement.upgrade(element) only upgraded the parentNode, not the children which were upgraded later on during the mutation observer cycle. You have to call upgradeAll or upgradeSubtree if you want to upgrade the children as well. Also, the element does not need to be added to the DOM so it works very well. This feature should be documented a little better.

**Comment by zanona** [comment]
Thanks @patrickmatte that was really helpful

**Comment by treshugart** [comment]
@zanona overriding `innerHTML` can be very tricky as WebKit (Safari) doesn't support accessing native property accessors, so you'd have to re-implement native HTML parsing. This is not something that is done lightly. We've done this in [our Shadow DOM Named Slot prollyfill](https://github.com/skatejs/named-slots/blob/master/src/index.js#L59) but it does degrade performance heavily on WebKit and has some other drawbacks.

If one had access to native accessors, it would still degrade performance because you'd supposedly want to `upgradeAll()`. There you have the overhead of:

1. userland function override
2. proxying native accessor
3. walking the entire tree

Without perf tests I can't say if that'd be acceptable, though. Quite possibly, but in my experience WebKit has been the deal breaker with things like this.

**Comment by zanona** [comment]
thanks for the heads up @treshugart. This is very interesting indeed.
I mocked something up quickly while working on it last week but didn't think of any implications since it seemed to work without problems. But as you said, it may be something much more complex with several drawbacks.

```js
const innerHTML        = Object.getOwnPropertyDescriptor(HTMLElement.prototype, 'innerHTML'),
      innerHTMLSet     = innerHTML.set;

innerHTML.set = function (value) {
  innerHTMLSet.call(this, value);
  self.CustomElements.upgradeSubtree(this);
};

Object.defineProperty(HTMLElement.prototype, 'innerHTML', innerHTML);

```

**Comment by treshugart** [comment]
No worries @zanona. If you find a simpler solution that what we've come up with that works in Safari, please share.

**Comment by zanona** [comment]
Hey @treshugart, it seems the shadowRoot polyfill is already overriding that here:

https://github.com/webcomponents/webcomponentsjs/blob/3ea23df8bc0f45d44fc903b706d379d7d50aba29/src/ShadowDOM/wrappers/ShadowRoot.js#L52-L55

Once the polyfill is loaded you can execute the script I mentioned earlier without problem on Safari since HTMLElement is then subclassed.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
