### ISSUE TITLE
IE11 Unable to get property 'replaceChild' of undefined or null reference

### ISSUE THREAD

**Issue by jshado1** [webcomponents/webcomponentsjs#518]
v0.7.21 causes the following exception to be thrown in IE11:

```js
SCRIPT5007: Unable to get property 'replaceChild' of undefined or null reference
File: webcomponents-lite.js, Line: 1037, Column: 9
```

The debugger says that `t` is `[object HTMLUnknownElement]`. I've been able to determine which custom element it's supposed to be based on `classList`. This seems to happen only for custom elements which extend native ones (but does not happen for all custom elements extending native ones). Ex `my-bar` and `my-foo` extend `a`, but only `my-bar` triggers this exception (`my-bar` always does and `my-foo` never does). Possibly a red-herring, but alphabetical order seems to matter (possibly due to our build process, which runs in alphabetical order, so my-bar would be included before my-foo).

v0.7.20 causes some Hierarchy error. v0.7.19 appears to be the last stable version.

Unfortunately, IE crashes when I try to create a jsbin for this.

**Comment by kevinpschaaf** [comment]
The root cause of the error looks to be the [addition of a patch](https://github.com/webcomponents/webcomponentsjs/commit/01c0f63153d63e9a4ef480a3fd6e77570630d709#diff-54de3c380d54ce0bd9573d2c2be463f0R201) to `document.importNode` in the Template polyfill that happens before a [separate patch](https://github.com/webcomponents/webcomponentsjs/commit/126a5d258634415e691b3f33b95b1c5c048dd2f7#diff-4e7daf874e5ea4b89427968f48f47784R24) of `document.importNode` that was added to specifically work around broken document fragments in IE (resulting in top-level children having no `parentNode`).  Due to ordering, the new Template polyfill `importNode` runs before the nodes in the doc fragment are fixed.

Since the `importNode` that fixes IE doc frags is in the CE polyfill but is actually unrelated to Custom Elements, we should just move that code to an earlier spot in the bundle.

**Comment by jasonhjohnson** [comment]
Hi. Was there a workaround for this?

**Comment by kito99** [comment]
Any progress on this? It sounds like a relatively simple fix...

**Comment by Torniojaws** [comment]
Still not working in IE11. Works in other browsers.

**Comment by russoturisto** [comment]
Yep, still broken.
