### ISSUE TITLE
attachedCallback is not invoked when moving a custom element from shadow root to body

### ISSUE THREAD

**Issue by platosha** [webcomponents/webcomponentsjs#519]
### Description

I am using Shadow DOM Polyfill. Given that I have a wrapper custom element with shadow root and an inner custom element inside the wrapper's shadow root. When trying to move inner to the document.body, only `detachedCallback` is invoked for inner, `attachedCallback` not invoked.
### Live Demo

Direct demo link: http://s.codepen.io/platosha/debug/qZpYXj

Source editor: http://codepen.io/platosha/pen/qZpYXj?editors=1010

Please watch the developer console log to see the issue.

The issue is in Shadow DOM Polyfill. Chrome has native Shadow DOM support, so the issue does not reproduce in Chrome, the demo works as expected, all callbacks are invoked. Compare with a browser without Shadow DOM native support.
### Steps to Reproduce
1. Wait until `wrap(document).__observer` is created  
2. Register the `'x-element'` custom element with logged callbacks  
   2.1. Create custom element prototype from `HTMLElement.prototype`  
   2.2. Add `attachedCallback` and `detachedCallback` to the prototype, with `console.log` calls in them  
   2.3. Register the custom element with the prototype  
3. Create the `wrapper` element with shadow root  
   3.1. Create the wrapper instance of `'x-element'`  
   3.2. Create shadowRoot inside the wrapper  
   3.3. Append the wrapper element to the `document.body`  
4. Create the `inner` element  
   4.1. Create the inner instance of `'x-element'`  
   4.2. Append the `inner` to the `wrapper`'s shadow root  
5. Wait until Mutation Observers triggered by the steps above are processed
6. Append `inner` to the `document.body`
#### Expected Results

Two lines in the console log:

```
  inner detachedCallback invoked
  inner attachedCallback invoked
```
#### Actual Results

Only one line in the console log:

```
  inner detachedCallback invoked
```
### Browsers Affected

All browsers except Chrome, which has native Shadow DOM.
### Versions

v0.7.20, also in master currently.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
