### ISSUE TITLE
WebComponentsReady is not being triggered inside hidden iframe on Firefox

### ISSUE THREAD

**Issue by alejost848** [webcomponents/webcomponentsjs#521]
I'm working on an app with multiple sections that get shown or hidden depending on the one selected. I have isolated a problem on Firefox when I try to get the WebComponentsReady event from an iframe that is hidden. Chrome and Edge output `Ready!` on the console, but Firefox outputs nothing.

Parent

``` javascript
<iframe src="test.html" hidden="true"></iframe>
```

Iframe

``` javascript
<script>
  window.addEventListener('WebComponentsReady', function(e) {
    console.log('Ready!');
  });
</script>
```

As soon as I unhide the iframe then the WebComponentsReady event is triggered. Is Firefox supposed to work that way or is it a bug within webcomponentsjs?

Thanks.

**Comment by bstmedia** [comment]
Its the same when loaded inside a custom element in polymer. Not cool.  Please advice. 

Parent
 `<my-notifications id="myNotification"></my-notifications>`

Content
 `<script>
  window.addEventListener('WebComponentsReady', function(e) {
    console.log('Ready!');
  });
</script>`

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
