### ISSUE TITLE
flags can not be overridden before loading

### ISSUE THREAD

**Issue by kewisch** [webcomponents/webcomponentsjs#528]
https://github.com/webcomponents/webcomponentsjs/blob/master/webcomponents.js#L22 suggests that if you define `noOpts` before loading, then options from `location.search` will not be loaded. This will never be the case though, since `flags` is initialized from an empty object.

This could be fixed by doing `var flags = window.WebComponents.flags;` which is initialized as an empty object by default a few lines up.

**Comment by Delagen** [comment]
+1

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
