### ISSUE TITLE
Element event listeners in IE 11 missing

### ISSUE THREAD

**Issue by GeorgeLung** [webcomponents/webcomponentsjs#532]
I'm using Angular and Polymer in the same application. For the polyfills in IE 11, the default event listeners seem to be replaced by `dispatchOriginalEvent`. However on some elements (in this case an `<input type="text" />`) the event listeners have been removed and nothing has been put back. So there is no notification of change or input events.

After a further look it seems that it's caused by the combination of angular's ng-include and the ShadowDOM polyfill within webcomponents.js. Within the ng-include some event listeners exist such as the click (created by ng-click) but not the ones require to bind to the value of an input text field (via ng-model)

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
