### ISSUE TITLE
TypeError: Object #<Performance> has no method 'now'

### ISSUE THREAD

**Issue by JonWallsten** [webcomponents/webcomponentsjs#539]
I got quite a few error messages in New Relic stating that performance.now is not a function.
Does window.performance guarantee that the method 'now' exists?
```
if (!window.performance) {
    var start = Date.now();
    window.performance = {
      now: function now() {
        return Date.now() - start;
      }
    };
  }
```

**Comment by Garbee** [comment]
Support is [pretty good](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now) across the browsers. Is there any way you could compare the errors to browsers and versions to see if they coincide with browsers that don't support it?

**Comment by JonWallsten** [comment]
All errors seem to originate from Android Browser 4.1-4.4.

**Comment by JonWallsten** [comment]
Also get this for "Mac Safari 5.1"
```
SyntaxError: Cannot declare a parameter named 'href'  in strict mode
```

**Comment by Garbee** [comment]
Safari 5 is not supported. Safari 7 is the minimum.

Does the Android issues occur *in* 4.4 or just up to and including 4.3? [Android 4.4](http://caniuse.com/#search=performance) is the first version with support. However, the direct Android browser is *not* supported by the polyfill so that is still not an issue for us to look into. The poyfill only supports *Chrome on Android* specifically. Newer versions of Android use Webview which can be updated independently to keep it evergreen, and they are using the same engine as Chrome so everything that works in newer Chrome on Android should work in Webview as well.

Overall, looks to me like you're hitting issues in unsupported browsers which means there is nothing that can or should be done internally to address them.

**Comment by JonWallsten** [comment]
The performance now issue happens on 4.4 as well. But it's no big deal. Just wanted to let you know what I found. We will not fix these either.

Thanks for taking the time.

**Comment by ebidel** [comment]
This looks like issues with older browsers. I know on older versions of Safari, `performance.now` doesn't exist, but that's going back further than the polyfills are meant to support.

**Comment by Garbee** [comment]
Thanks for adding that check @ebidel. At least it is one less thing getting into logs.
