### ISSUE TITLE
Seperate polyfill repos and NPM packages

### ISSUE THREAD

**Issue by jaydenseric** [webcomponents/webcomponentsjs#565]
There are no instructions for how to import and use this package or it's individual polyfills via NPM.

It looks like the webcomponents.js [Template polyfill](https://github.com/webcomponents/webcomponentsjs/tree/master/src/Template) is the best one available, but you can't add it as a NPM dependency to a project and import it without pulling in all of webcomponents.js.

Also, it is difficult to find issues relating to this specific polyfill scanning through 199 mostly unrelated open issues.

If the individual polyfills were available separately, this main project could still import and bundle them all in webcomponents.js.

Ideally you could do something like:

```
npm install html-template-polyfill --save
```

And then at the start of your ES6 app.js:

``` js
import 'html-template-polyfill'
```

**Comment by jaydenseric** [comment]
In the [HTML Templates caniuse entry](http://caniuse.com/#feat=template) the polyfill under *Resources* unhelpfully links to polymer-project.org homepage, probably because there is no specific place to find it.

**Comment by notwaldorf** [comment]
@jaydenseric I've moved the `Template.js`polyfill to its own repo (webcomponents/template), and I've asked @justinfagnani to publish it to npm. For `v1` we've separated all the polyfills in specific repos, but it's unlikely we're going to do this for `v0` at this point :(

Closing since I don't think there's an action left here :(
Soooo going to close

**Comment by jaydenseric** [comment]
Great news, thanks!
