### ISSUE TITLE
Syntax error in webcomponentjs on IE11

### ISSUE THREAD

**Issue by pongsakornv** [webcomponents/webcomponentsjs#566]
I'm not sure where to ask this... but I use the yeomangenerator-polymer template(https://github.com/yeoman/generator-polymer) and deploy it to tomcat server right-away without customizing.

Chrome/FF is fine... but for IE (I use IE11) I got these errors instead

SCRIPT1003: Expected ':'
File: webcomponents.js, Line: 791, Column: 11

> TreeScope.prototype = {
>      get renderer() {  //<<<< this line
>        if (this.root instanceof scope.wrappers.ShadowRoot) {

and

SCRIPT438: Object doesn't support property or method 'addEventListener'

and the result is messed up. I tried both webcomponents.js and webcomponents-lite.js and got the same result.

I finished reading about the browser compatibility and I think it seems odd for webcomponentsjs to die so easily like this... Did I miss something?

Thanks for helping me.

**Comment by kanariezwart** [comment]
Same issue here.

**Comment by pdoronila** [comment]
Same issue here

**Comment by jhuesos** [comment]
I have seen this error as well, but it is not always reproducible.

**Comment by Rudolphous** [comment]
same issue here

**Comment by dmitriyilin** [comment]
I experienced the same kind of issue with IE 11. In my case the reason was in IE's "Compatability Veiw". The browser emulated "Document mode": 7.

You can check "Document mode" in developer tools in "Emulation tab".

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
