### ISSUE TITLE
Properties/Methods not added to the Custom Element Prototype

### ISSUE THREAD

**Issue by jshcrowthe** [webcomponents/webcomponentsjs#580]
When the Web Components Polyfill is loaded asynchronously/conditionally the properties/methods defined in the custom element prototype are not added to the existing elements.

I took the example from [this article on WebComponents.org](http://webcomponents.org/articles/introduction-to-custom-elements/#adding-features-to-a-custom-element) and put it in an empty [JSBin](http://jsbin.com/rihawu/1/edit?html,output). I then created a file to consume that via HTML Import (so that file should not be loaded until after the Web Components polyfill has loaded).

With the `async` attribute on the polyfill the `alert` button doesn't work, however if you remove it (and block parsing to load the polyfill) everything works fine.
### JSBin
- `async` loading: http://jsbin.com/yamocop/11/edit?html,output
- Conditional loading: http://jsbin.com/yamocop/12/edit?html,output
### Browsers
- Reproduced in Firefox and Safari
- Chrome works fine

**Comment by jshcrowthe** [comment]
I've dug into this a little more and have some more information.

So in the linked `JSBin`s I am using `webcomponents.js` (including Shadow DOM). In the polyfill there is a section where the browser [selection mechanisms are wrapped](https://github.com/webcomponents/webcomponentsjs/blob/3ea23df8bc0f45d44fc903b706d379d7d50aba29/src/ShadowDOM/wrappers/Document.js#L282-L328) which got me thinking it may be a selector issue.

So I took a look and if I delay the execution of this code:
```javascript
    var xComponent = document.querySelector('x-component');
    var button = document.querySelector('button');
    button.addEventListener('click', function(e) {
      xComponent.alert();
    });
```

Till after the `WebComponentsReady` event then the code functions just fine (_I really only need to delay the execution of `document.querySelector('x-component')`_).

That said, if I load `webcomponents-lite.js`, the page functions as expected (no need to wait for the `WebComponentsReady` event).

In the README.md of this repo it does mention something related to this behavior:
> The webcomponents.js and webcomponents-lite.js polyfills parse element definitions and handle their upgrade asynchronously. If prematurely fetching the element from the DOM before it has an opportunity to upgrade, you'll be working with an HTMLUnknownElement.

However because the elements are upgraded in place (at least in `webcomponents-lite.js`) existing references to those elements, as long as they aren't accessed till after element upgrade, should remain functional IMO.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
