### ISSUE TITLE
FR: Change exported functions that use `this` to prototype methods

### ISSUE THREAD

**Issue by choumx** [webcomponents/webcomponentsjs#625]
Can cause silent failures when compiled with Closure using ["advanced optimizations"](https://developers.google.com/closure/compiler/docs/limitations#implications-of-object-property-flattening):

> To prevent property flattening from breaking your references to this, only use this within constructors and prototype methods.

For example, `this` is used in `ShadowCSS` in non-prototype functions. This results in `this` becoming the `Window` global instead of the expected `ShadowCSS` object when compiled with Closure using advanced optimizations.

Context: https://github.com/ampproject/amphtml/pull/5191

If you guys think this is a good idea, I can work on a PR to refactor `ShadowCSS`.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
