### ISSUE TITLE
In v1, doing a document.write to load modules doesn't work with async scripts

### ISSUE THREAD

**Issue by ruphin** [webcomponents/webcomponentsjs#638]
This can be a problem for dynamically loading the polyfills only if they are needed at runtime. e.g. this does not work:

``` javascript
     if ('registerElement' in document
         && 'import' in document.createElement('link')
         && 'content' in document.createElement('template')) {
       // platform is good!
     } else {
       // polyfill the platform!
       let e = document.createElement('script');
       e.src = '/vendor/webcomponentsjs/webcomponents-lite.js';
       document.body.appendChild(e);
     }
```

**Comment by ruphin** [comment]
(wiled by @rictic at polymer summit /cc @justinfagnani )

**Comment by YvanDaSilva** [comment]
It will not work either if you try to load them by using the <script> tag in your page when serving on localhost if the console is open.

[Violation] Parser was blocked due to document.write(<script>) webcomponents-lite.js:70
[Violation] Parser was blocked due to document.write(<script>) html-imports.js:49

Also we shouldn't use document.write to load scripts as there is a bunch of reasons against it apparently https://developers.google.com/web/updates/2016/08/removing-document-write

Concerning the chrome error, not sure if it is intended by ( https://chromium.googlesource.com/chromium/src.git/+/master/third_party/WebKit/Source/core/frame/PerformanceMonitor.cpp#125 ) but it is always triggered when the console is open. Maybe we should open an issue over there.

**Comment by TimvdLippe** [comment]
I think this issue has been resolved, given that we have written our own loader: https://github.com/webcomponents/webcomponentsjs/blob/master/webcomponents-loader.js

**Comment by AStoker** [comment]
Hate to drudge up an old issue, but I'm running V2.1.0 and I get this issue (in Firefox currently) only occasionally:
`A call to document.write() from an asynchronously-loaded external script was ignored.`
This is in reference to this [line](https://github.com/webcomponents/webcomponentsjs/blob/0534101d277e191ef483ff2a3f1f23838bc9c019/webcomponents-loader.js#L162)
```javascript
document.write(newScript.outerHTML);
```
Ideas? Need to be a new issue?
