### ISSUE TITLE
Question: should the mutation observer polyfill catch all the mutations the native implementation would?

### ISSUE THREAD

**Issue by sarukuku** [webcomponents/webcomponentsjs#639]
I'm probably just stupid but I'll ask anyway. 

Let's pretend that I have the following code in page head:

```
var observer = new MutationObserver(function(mutations) {
  for (var i=0; i < mutations.length; i++) {
    for (var j=0; j < mutations[i].addedNodes.length; j++) {
      checkNode(mutations[i].addedNodes[j]);
    }
  }
});

observer.observe(document.documentElement, {
  childList: true,
  subtree: true
});

var checkNode = function(addedNode) {
  if (addedNode.nodeType === 1){
    console.log(addedNode)
  }
}
```

In latest Chrome f.ex. it logs quite a few nodes on a "normal" page. If I import MutationObserver polyfill from this repository and switch the native `new MutationObserver` with `new JsMutationObserver` and run the same code in the same browser it logs much less nodes to the console.

My only questions are: is the difference intended and if it is, why?

**Comment by sarukuku** [comment]
To me it seems the native `MutationObserver` catches all mutations that happen during initial DOM creation and `JsMutationObserver` doesn't. Don't know if I'm right though.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
