### ISSUE TITLE
Be more specific on browser compatibility

### ISSUE THREAD

**Issue by zenorocha** [webcomponents/webcomponentsjs#65]
I think it's valuable to include more information about browser support in the README and in the [webcomponents.org/polyfills](http://webcomponents.org/polyfills) page.

Is this list up to date? https://www.polymer-project.org/resources/compatibility.html

**Comment by janerivi** [comment]
Still no info on the main readme on the frontpage of this project. This is supposed to be a polyfill to support older browser - but where it the information on wich older browser versions are actually supported. This is a mystery to me. Is it because no-one actually knows. It would help people make decisions. IE9 support would be very useful now, but it seems like its not working for that browser. If it goes back to IE10 it is ok and would make the polyfill broadly useful in 2016 when IE9 looses its backing from Microsoft. But for now - the only way to find out is to try and build something with polymer yourself and open up the old browsers to do a test. Mabe it works nicely in the test and one believe the browser is supported, but then later on in the project one discovers that some aspects of webcomponents wont work after all.

**Comment by shadowmint** [comment]
fwiw note that firefox has officially stated it will never implement html imports (see https://bugzilla.mozilla.org/show_bug.cgi?id=877072), so it's unclear what the future holds both for web components.

**Comment by zenorocha** [comment]
:tada:
