### ISSUE TITLE
Improper life cycle order

### ISSUE THREAD

**Issue by truefusion** [webcomponents/webcomponentsjs#652]
Proper life cycle order ensures that child elements are ready and attached to the parent element before the parent element is ready and attached to the DOM, allowing us to do some needed preparation before the parent tries to communicate with its children.

For example, in Chrome we observe:
```
parent-element created!
child-element created!
child-element ready!
parent-element ready!
distributed-element created!
distributed-element ready!
child-element attached!
parent-element attached!
distributed-element attached!
```

Where the need for a polyfill exists we observe:
```
parent-element created!
child-element created!
distributed-element created!
distributed-element ready!
child-element ready!
parent-element ready!
parent-element attached!
child-element attached!
distributed-element attached!
```

In the latter case child-element is attached after parent-element is attached to the DOM, and distributed-element is made ready before child-element, when it should be ready after parent-element is ready.

This was produced with the following code:
**import-ready-attached.html**
```
<link rel="import" href="/bower_components/polymer/polymer.html">

<script>
	B = {
		attached: function() { console.log(this.is, 'attached!'); }
	,	created: function () { console.log(this.is, 'created!'); }
	,	ready: function () { console.log(this.is, 'ready!'); }
	}
</script>

<dom-module id="parent-element">
	<template><child-element></child-element><content></content></template>
	<script>Polymer({ is: 'parent-element', behaviors: [B] });</script>
</dom-module>

<dom-module id="child-element">
	<template><content></content></template>
	<script>Polymer({ is: 'child-element', behaviors: [B] });</script>
</dom-module>

<dom-module id="distributed-element">
	<template><content></content></template>
	<script>Polymer({ is: 'distributed-element', behaviors: [B] });</script>
</dom-module>
```

Test:
```
<!DOCTYPE html>
<html>
<head>
	<script src="/bower_components/webcomponentsjs/webcomponents-lite.min.js" async></script>
	<link rel="import" href="import-ready-attached.html">
</head>
<body>
	<parent-element>
		<distributed-element></distributed-element>
	</parent-element>
</body>
</html>
```

**Comment by notwaldorf** [comment]
@truefusion Is this for the `v0` or `v1` version of the polyfill? (i.e. the master branch/a release tag, or the `v1` branch?

**Comment by truefusion** [comment]
I was using v0.7.23 of webcomponentsjs at the time of the report.

**Comment by notwaldorf** [comment]
Thanks!

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
