### ISSUE TITLE
Polyfill should not depend on Polymer

### ISSUE THREAD

**Issue by wamoyo** [webcomponents/webcomponentsjs#668]
It seems to me the webcomponents polyfill should stand alone.

It's just misleading. I went to webcomponents.org to learn about web components, I can't even run the first example in the guide on Firefox without polymer. Not to mention installing gulp and bower, which are great pieces of technology, but when you require developers to adopt specific workflows you make something less accessible.

If it's going to be a web standard it has to be maximally accessible. 

Tangible suggestion: Have a standalone polyfill that can be dropped in a script tag, and makes modern browsers run web components.

**Comment by notwaldorf** [comment]
The polyfill itself does not depend on Polymer, and can be used without Polymer just fine, and can absolutely be dropped in a script tag. Here is an example of that: http://jsbin.com/kavexaf/edit?html,output

Which example are you referring to? If it's [this](https://www.webcomponents.org/introduction#how-do-i-use-a-web-component-) one, then that element used in the example _is_ a Polymer element in particular; to use Polymer elements, you need to import Polymer, and the easiest way to obtain them is through `bower`. But that seems like an issue you would have with a Polymer element, not with the polyfill.

Closing, since I think there's a misunderstanding between using the polyfill, and using a web component built with Polymer. Please re-open this or comment if you have any more questions!

**Comment by wamoyo** [comment]
Great, thanks so much! It is the first example in the introduction, and there's no mention of needing polymer, so that threw me off. 

Thanks for sharing the example :+1:

**Comment by notwaldorf** [comment]
No worries! Glad this helped :)
