### ISSUE TITLE
Unable to load webcomponents.js in blackberry access browser on ios

### ISSUE THREAD

**Issue by anivas** [webcomponents/webcomponentsjs#683]
I have an empty html page with just webcomponents.js included. The page is failing to load and the stacktrace points to **getElementsByTagNameFiltered**: _root instanceof scope.wrappers.ShadowRoot_. The error is **TypeError: Right-hand side of 'instanceof' is not an object**. Is this a known issue.Do we have a work around or possible fix for this.

Note: The same code works on blackberry access browser on android on all devices.

Thanks.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
