### ISSUE TITLE
<content>s in the inside of <table> are lost. (IE11)

### ISSUE THREAD

**Issue by mysticatea** [webcomponents/webcomponentsjs#69]
Code: http://jsbin.com/zapej/4/edit?html,output

Copied from https://github.com/Polymer/ShadowDOM/issues/517

On IE11, when I appended an element into a custom element by `appendChild` method, if `<content>` is in a table cell, the appended element is lost.

For the appended element:
- `getElementById` returns null.
- No display.
- But we can find in `innerHTML`.

**Comment by mysticatea** [comment]
I'm worried that this issue might be forgotten.

I made new repro code, only ShadowDOM (without Custom Elements).
Code: http://jsbin.com/cocaxigamo/2

Please click twice a button "move child" on IE11.
When 1st click, will move the `div#child` element into the `div#parent` element.
When 2nd click, will occur an error, because `document.getElementById("child")` returned `null`.

Now, I move `<content>` elements in ShadowDOM to outside of `<table>`.
Code: http://jsbin.com/cocaxigamo/3

Then this code is run as I intended.

.... I'm trying to make a test, but haven't reproduced yet.
https://github.com/mysticatea/webcomponentsjs/commit/e210e0b5033bfd7299ac9dba0cadba3bfc44fae4
This test is passed on IE11.

Ummm....

**Comment by mysticatea** [comment]
I'm investigating this problem.
I will report some things that I realized.

## Reproduce Situation

* There is a `<content>` element in ShadowDOM.
* The `<content>` element doesn't have distributed nodes.
* There is the `<content>` element in the inside of a `<table>` element.
* The previous node of the `<content>` element is a **text node**.

1. `ShadowRenderer::render` > `RenderNode::sync` > remove the `<content>` element from native DOM tree, and update its wrapper's `nextSibling_` & `previousSibling_` properties.
2. IE11 **renews instances of text node in the inside of a table element silently** -- destroy and create -- that's becomes other instance.
3. Then those wrappers become other instance.  References of `nextSibling_` & `previousSibling_` of the text nodes are lost.  Reference to the `<content>` element is lost.

**Comment by mysticatea** [comment]
Oh, do how to fix this...

**Comment by jmesserly** [comment]
excellent report. Yeah, that's going to be tricky to fix. Probably, we need some special code to handle this situation in IE11 tables, and re-associate text nodes. Looking into this

**Comment by jmesserly** [comment]
here's a workaround, put the text content in `<span>`: http://jsbin.com/nucuxeyava/1/edit
would that work for you?

**Comment by mysticatea** [comment]
OK, I add a workaround into my code.
I will use comment nodes.

```html
<template>
  <table>
    <tr>
      <td>
        <!----><content></content><!---->
      </td>
    </tr>
  </table>
</template>
```

And I made a quick fix for this issue: https://github.com/mysticatea/webcomponentsjs/commit/ae0c3bc0b65e85a25c93f087e5f3bb3b560f93a4

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
