### ISSUE TITLE
Package names

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [webcomponents/webcomponentsjs#708]
Bower package (see `bower.json`) uses `webcomponentsjs` (withot dot) name, but NPM package (see `package.json`) uses `webcomponents.js` (with dot) name.

I suggest without dot. :)

Should we use the _same package name_ for both, Bower and NPM packages?

BTW, should this package be published on NMP in [@webcomponents](https://npmjs.com/~webcomponents) scope as `@webcomponents/webcomponents.js` or `@webcomponents/webcomponentsjs` like `@webcomponents/custom-elements`, `@webcomponents/shadydom` and `@webcomponents/shadycss` instead of simply `webcomponents.js` or `webcomponentsjs`?

If we use [@webcomponents](https://npmjs.com/~webcomponents) scope, we can use more short name `webcomponents` (without dot and without `js` at all) like `@webcomponents/webcomponents`.

BTW, what about renaming [custom-elements](https://github.com/webcomponents/custom-elements) package to more short `customelements` (without hyphen)? None of `shadydom` and `shadycss` do not use hyphen in names like `shady-dom` and `shady-css`.

**Comment by FluorescentHallucinogen** [comment]
@azakus, PTAL.

**Comment by FluorescentHallucinogen** [comment]
BTW, currently `template` in Bower points to https://github.com/jgallen23/template. What about renaming https://github.com/webcomponents/template to `html-template` and use the same package name in Bower and NPM? ;)

**Comment by FluorescentHallucinogen** [comment]
@justinfagnani, @notwaldorf, PTAL.

**Comment by FluorescentHallucinogen** [comment]
I.e. we need some consistency in package naming.

1. We should use the same names for packages in Bower and NPM.
2. We should publish all packages in @webcomponents scope.
3. We should use `-polyfill` postfix in package names (e.g. `customelements-polyfill`, `htmltemplate-polyfill`, `htmlimports-polyfill`, etc.).

**Comment by FrozenPandaz** [comment]
Would also like this published to NPM soon.

**Comment by justinfagnani** [comment]
@FluorescentHallucinogen the `webcomponentsjs` name (without a dot) is not owned by us, so we can't use that. Maybe @dlmma could update it.

I think that given the prevalence of people publishing other's package names, it's probably best to use the `@webcomponents` scope, and then we could use a shorter name, like `loader`. I don't agree with useing `customelements` over `custom-elements` because it's only one character shorter and harder to read.

**Comment by Hotell** [comment]
Guys can you move forward with this pls asap? 

I don't want to troll or anything, but it's 2017 and you are not able to publish things on npm ? I mean what's the problem? I understand "issues" with releasing polymer stuff on npm because you relly on bower and relative paths in those packages, but otherwise...

All of this makes me just sad and is really hard to evangelise web components in the world full of solutions that work out of the box ( react + ecosystem, angular + ecosystem, vue ... ).

✌️

**Comment by seaneking** [comment]
Am I missing something? Won't the existing `webcomponents.js` package be updated when 1.0 mainline is released? What does it matter if it's published as webcomponents.js or a scoped package? Tbh I prefer the existing one - it's shorter, only inconsistent with the Bower package, and Bower is being [deprecated](https://bower.io/)  anyway.

Would love to see webcomponentsjs move away from Bower though - can't see a reason to be so tightly coupled (eg: [these imports](https://github.com/webcomponents/webcomponentsjs/blob/master/entrypoints/webcomponents-hi-sd-ce-index.js#L17)) to it for a pure js lib like this. Most libs/ecosystems are standardising on NPM, and you could still support Bower by just leaving dist files committed like they currently are.

**Comment by TimvdLippe** [comment]
We are now publishing to npm under the `@webcomponents` scope. Support for Bower has been removed.
