### ISSUE TITLE
Rename webcomponents-es5-loader to webcomponents-es5-transpiled-loader

### ISSUE THREAD

**Issue by azakus** [webcomponents/webcomponentsjs#722]
The name is a bit confusing, as people _do not_ need to use the es5 loader unless they have transpiled code.

**Comment by justinfagnani** [comment]
That's a long name...

Maybe we can make things more clear by renaming the other loader to webcomponents-es6-loader?

Then we can say:

|Deployed Code | Loader | Supported Browsers |
|:-|:-|:-|
| ES5 | webcomponents-es5-loader.js | All |
| ES6 | webcomponents-es6-loader.js | Latest Chrome, Safari, FF, Edge |
| ES5* | webcomponents-es6-loader.js | IE, Older Safari, etc  |

* You can do this if you're using differential serving to serve ES6 to the latest browsers and ES5 to older browser.

I like this because the only non-completely-straightforward case is the third row, which we could normally just omit, and is the advanced case.

**Comment by CaptainCodeman** [comment]
Yeah, please have es5 and es6 for consistency ... it makes things neater and easier to set a single value and then use it in the URL for the polyfill and as the folder for built files (just experimenting with detecting the version to use on the browser so Chrome etc... can use the es6 versions while still serving es5 to older browsers - seems to work OK!)

**Comment by azakus** [comment]
As I was saying in https://github.com/webcomponents/webcomponentsjs/issues/737#issuecomment-288191881, I think the better approach is to only have one loader, and require the user to put `native-shim` just before the loader if they compile.
It feels simpler to explain that way.

**Comment by azakus** [comment]
Closing in favor of #741
