### ISSUE TITLE
_currentScript not working inside createdCallback on declared elements

### ISSUE THREAD

**Issue by ghost** [webcomponents/webcomponentsjs#73]
On my machine (Mac OS X 10.10, Chrome 38), document._currentScript inside of an HTML import is not working correctly inside of a createdCallback for elements instantiated declaratively.

I instantiate some custom elements in the body of my main HTML file (the one that imports my custom elements).  In the head of that same HTML file, I load an external Javascript file.

Inside a script tag in my custom element, I declare a customCallback on the Javascript object serving as my custom element's prototype.

If I console.log document._currentScript inside the customCallback, I can watch as for the first few elements it logs the script tag of the external script referenced in my main document, and then an HTMLScriptElement object for that same external script.  Neither of those matches the expected behavior of returning the HTMLScriptElement for the actual script tag in the imported element where the customCallback is declared.

**Comment by DestyNova** [comment]
Using the polyfill in Firefox (38.0a2) gives the "outer" document instead of the imported one.
Evaluating both "document._currentScript.ownerDocument.URL" and "document.currentScript.ownerDocument.URL" returns the URL of the outer document.

In fact I can't see any way to get a reference to the child document, either from Javascript in its body or loaded from a JS file in the child document's header.

**Comment by noopole** [comment]
It seems normal on Firefox (cf. MDN currentScript) : 
"It's important to note that this will not reference the <script> element if the code in the script is being called as a callback or event handler; it will only reference the element while it's initially being processed."

There's a proposed workaround here : https://github.com/JamesMGreene/currentExecutingScript

**Comment by xorcus** [comment]
I hit the same issue and figured out the same workaround :-)

- `index.html` links `webcomponents.min.js`
- `index.html` imports `my-example.html`
- `my-example.html` links `my-example.js`
- `my-example.js` registers a custom element and tries to access `document._currentScript.ownerDocument`

If accessed outside of the callbacks (e.g. saving a reference in the closure for later use), it works as expected. If accessed inside the `createdCallback`, `document._currentScript` seems to refer to `<script src="webcomponents.min.js"></script>` in `index.html`, probably because that's where it's being called from. When you think about it, it may arguably make some sense, because that's the currently running script when the callback gets executed. Still, it was not what I expected :-)
