### ISSUE TITLE
sourcemaps are compiled using es6

### ISSUE THREAD

**Issue by astateful** [webcomponents/webcomponentsjs#776]
Currently webcomponentsjs distributes the sourcemaps based on ES6 code, however they break when loaded in Internet Explorer 11. Currently the only option is to not copy over the sourcemaps for the webcomponents when preparing the final build, however then our server receives errors since IE11 as well as other browsers are attempting to request the sourcemap for the given minified file.

**Comment by justinfagnani** [comment]
What's the solution here? The sourcemaps only exist because we're compiling ES6 to ES5.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
