### ISSUE TITLE
Unable to read the value of a custom component in safari 10

### ISSUE THREAD

**Issue by danielrasmuson** [webcomponents/webcomponentsjs#792]
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.7.24/webcomponents.min.js"></script>
</head>
<body>

<script>
const toggleSwitchPrototype = Object.create(HTMLElement.prototype)
toggleSwitchPrototype.attachedCallback = function() {
  this.value = 'value in chrome but not safari';
}
document.registerElement('dd-toggle', { prototype: toggleSwitchPrototype })
</script>

<dd-toggle></dd-toggle>
<div>
  ddtoggle value: <span id="dd-toggle-value"></span>
</div>

<script>
document.querySelector('#dd-toggle-value').innerHTML = document.querySelector('dd-toggle').value;
</script>
  
</body>
</html>
```

**Result in Chrome**
`ddtoggle value: value in chrome but not safari`

**Result in Safari**
`ddtoggle value: undefined`

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
