### ISSUE TITLE
SCRIPT1002: Syntax error in IE11 when including custom-elements-es5-adapter.js

### ISSUE THREAD

**Issue by svastanesto** [webcomponents/webcomponentsjs#795]
When custom-elements-es5-adapter.js is included on the page the IE 11 gives syntax error. 

**SCRIPT1002: Syntax error**
**File: custom-elements-es5-adapter.js,** Line: 4, Column: 4

The page will render normally, but the error will show in the console. In my case that is preventing tests from running since their execution breaks directly on the first syntax error. 

I see that this issue was addressed and fixed for Polymer users https://github.com/webcomponents/webcomponentsjs/issues/749, but when will it be addressed for non-Polymer users of webcomponetsjs? 

Thanks!

**Comment by 18steps** [comment]
You should not load `custom-elements-es5-adapter.js` in IE11

From https://github.com/webcomponents/webcomponentsjs/issues/900#issuecomment-380832441 :

> Use the custom elements polyfill on all browsers that _don't_ have native custom elements.
> Use the custom-elements-es5-adapter on browsers that _do_ have native custom elements that you want to deploy custom elements classes compiled to ES5 to. Or deploy ES6 to browsers that support it.

**Comment by CITguy** [comment]
With the dependency update to `@webcomponents/custom-elements` version `1.2.0` (988d4a149f5049b9fcf46b5a34528c9538d1acd7), you should be able to load the adapter without additional effort.

The adapter was modified to replace the ironically-used ES6 `class` syntax with a `Reflect`-based solution ([`fea35b08`](https://github.com/webcomponents/custom-elements/commit/fea35b08cb989f3f0a21b0ade8aa0f15f93bc49d)).

The following should work as of `@webcomponents/webcomponents` versions `v1.2.4` and `v2.0.4`.

## TL;DR
```html
<head>
  <!-- ... -->
  <link rel="stylesheet" href="path/to/application-styles.css" />

  <script src="path/to/node_modules/@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js"></script>
  <script src="path/to/node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js"></script>
  <!-- polyfills for the current browser get injected here (if needed) -->
</head>
<body>
  <!-- ... -->

  <script src="path/to/application-logic.js"></script>
</body>
```

## Updates to your markup

Instead of the `<span>` hack:

```html
<span id="ce-es5-adapter">	
  <script>	
    if (!window.customElements) {	
      var elAdapter = document.querySelector('#ce-es5-adapter');	
      elAdapter.parentElement.removeChild(elAdapter);	
    }	
  </script>	
  <script src="path/to/custom-elements-es5-adapter.js"></script>	
</span>
```

You can just load the adapter directly:

```html
<script src="path/to/custom-elements-es5-adapter.js"></script>
```

**Comment by TimvdLippe** [comment]
@18steps is correct. The adapter is intended for browsers that DO support ES6. Do not load the adapter in IE11 or an environment which only supports ES5. For more information see https://github.com/webcomponents/webcomponentsjs#custom-elements-es5-adapterjs
