### ISSUE TITLE
iPad 4 Safari Bugs

### ISSUE THREAD

**Issue by codejamninja** [webcomponents/webcomponentsjs#805]
I am having trouble getting webcomponents to work on iPad 4 Safari.  I am using the latest stable version v0.7.24. I get the following error.

```
TypeError: Attempting to define property on object that is not extensible.set
```

![2017-06-25-052028_1366x768_scrot](https://user-images.githubusercontent.com/6234038/27515385-a175a558-5967-11e7-9abe-b3531c9cd7ed.png)

I've traced the error to webcomponents-lite.js:584

```js
if (entry && entry[0] === key) entry[1] = value; else defineProperty(key, this.name, {
  value: [ key, value ],
  writable: true
});
```

The value for the `entry` variable is `undefined`
The value for the `key` appears to be an empty string when printed to the console, but its type is listed as an object.

I was able to get it to work by wrapping the code in a try catch.

```js
try {
  if (entry && entry[0] === key) entry[1] = value; else defineProperty(key, this.name, {
    value: [ key, value ],
    writable: true
  });
} catch(err) {
  console.error(err);
}
```

The err returned was completely empty

I tried using the 1.0.0 version of webcomponents, however, I received the following error.

```
ReferenceError: Can't find variable: Set
```

![2017-06-25-051152_1366x768_scrot](https://user-images.githubusercontent.com/6234038/27515404-d2cc43e6-5967-11e7-95ff-b46c0d9a92e4.png)

The error is located at webcomponents-lite.js:147

I didn't even attempt to debut it because the code is minified.

**Comment by jamrizzi** [comment]
I forked the repo and created a patch in case anyone runs into this same issue and needs an immediate fix.

https://github.com/jamrizzi/webcomponentsjs-safari-patch

Add the webcomponentsjs dependency to your bower.json like so
```json
{
  "dependancies": {
    "webcomponentsjs": "webcomponentsjs-safari-patch#^0.7.26"
  }
}
```

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
