### ISSUE TITLE
Opacity not working on Safari when dynamically added onto a child item via a class

### ISSUE THREAD

**Issue by liam-swinney** [webcomponents/webcomponentsjs#807]
I've noticed a bug with Web Components in Safari (Version 10.1.1 (12603.2.4)) and I want to see if it's known, and if not, whether it's a bug with Web Components or Safari itself then report it in the appropriate place.

The bug is when you add a class within a delay using something like 'setTimeout' which has an opacity change for a child element, then it doesn't take effect. However, when I inspect element, I can see that it states opacity is correct (That it is 1) and if I change this value directly in the dev tools then it works as expected. This isn't an issue on the parent :host element, only the child.

As seen in the pen below, I've managed to also see a bit of a hacky way around it by manipulating the style of the element prior.  Line 77 is where the different scenarios for the class is added.
https://codepen.io/anon/pen/ZyvyeK?editors=1001#0

This works as expected in Chrome

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
