### ISSUE TITLE
TypeError: Attempted to assign to readonly property at custom-elements-es5-adapter.js

### ISSUE THREAD

**Issue by kelvinwatson** [webcomponents/webcomponentsjs#808]
I'm getting the following error in Safari 10.1.1

```
TypeError: Attempted to assign to readonly property
```
The error is originating from `custom-elements-es5-adapter.js:40:283`. I am using webcomponentsjs v1.0.0.

Any help would be appreciated. Thanks!

**Comment by jamrizzi** [comment]
Dang bro, I get that same error on the iPad 4 version of Safari. I wrote more details about the bug in issue #805.

I forked the repo and created a patch in case anyone runs into this same issue and needs an immediate fix.

https://github.com/jamrizzi/webcomponentsjs-safari-patch

Add the webcomponentsjs dependency to your bower.json like so
```json
{
  "dependancies": {
    "webcomponentsjs": "webcomponentsjs-safari-patch#^0.7.26"
  }
}
```

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
