### ISSUE TITLE
Error: Assignment to read-only properties is not allowed in strict mode in IE11

### ISSUE THREAD

**Issue by Jason0826** [webcomponents/webcomponentsjs#825]
When I test web-component in IE 11 
I saw this is ERROR:
```
Assignment to read-only properties is not allowed in strict mode
[in webcomponent-lite.js]
```
I'm using 
```
      "@webcomponents/webcomponentsjs/webcomponents-lite",
      "@webcomponents/webcomponentsjs/custom-elements-es5-adapter",
```
Any idea?

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!

**Comment by web-padawan** [comment]
BTW, this happens when you try to set `style` property, e.g.
```
this.style.display = 'block';
```
The attribute should be used instead:
```
this.setAttribute('style', 'display: block')
```

There might be more such cases.
