### ISSUE TITLE
Question:  what's the difference between native-shim.js and custom-elements-es5-adapter.js

### ISSUE THREAD

**Issue by Jeff17Robbins** [webcomponents/webcomponentsjs#842]
The custom elements polyfill has [native-shim.js](https://github.com/webcomponents/custom-elements/blob/master/src/native-shim.js).   But this aggregate repo has [custom-elements-es5-adapter.js](custom-elements-es5-adapter.js).

Is there a difference between the two, in that they look similar?  Has custom-elements-es5-adapter.js supplanted native-shim.js?

**Comment by Jeff17Robbins** [comment]
I looked at the build and saw that custom-elements-es5-adapter.js is built from

```
import '../node_modules/@webcomponents/custom-elements/src/native-shim.js';
```

**Comment by snuggs** [comment]
@Jeff17Robbins great question! If I Remember Correctly the `native-shim.js` is used for ensuring the `HTMLElement` which is inherited from calls `super()` which is part of the spec. `v1` Custom Elements has a hard dependency on using ES6 classes. So if you get any component implementation that has been transpiled you are kinda hosed. That said there is one caveat. This clearly doesn't work in browsers that do not support classes. (i.e. I.E.). Therefore transpiling `native-shim.js` leaves you in the same predicament the shim attempts to alleviate. I hope this sheds some light on the situation because we have discussed this ad nauseam and have bumped into every wall you could possibly imagine. To be clear we are 💯 % in a "transition period" as long as IE11 is around. That's basically what all of this is for. Do keep in mind must polyfill `window.customElements` as well for browsers that do support classes but don't support the `CustomElementsRegistry` ... yet. (i.e. Firefox _behind nightly flag_). But that's another story. /cc @brandondees
