### ISSUE TITLE
Polymer 2:Firefox DOM , add random number as id to my custom elements

### ISSUE THREAD

**Issue by mrraval008** [webcomponents/webcomponentsjs#845]
Hello Guys,
I am converting my polymer 1 application to polymer 2 legacy mode.
Only for Firefox browser some random number is get added to my element ex.  ,`<custom-element **id="faec5fbf0c0fb0c6"** noink="" dropdown-icon=""></custom-element>`,It is overwriting already defined ID.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
