### ISSUE TITLE
problem w/ appendChild

### ISSUE THREAD

**Issue by robrez** [webcomponents/webcomponentsjs#856]
In a polymer 2.0 project built using the `es5-bundled` preset, some code is generating a `NoModificationAllowedError` in IE11.

The exception occurs when an element is appended to a new parent using `appendChild`. _Note: the exception is not generated if the element is first removed from its current parent._

General setup is:

```
<template>
  <div id="a">
    <x-element id="x"></x-element>
  </div>

  <div> id="b">
  </div>
</template>

...

  var a = this.shadowRoot.querySelector("#a");
  var b = this.shadowRoot.querySelector("#b");
  var x = this.shadowRoot.querySelector("#x");

  if (x.parentNode) {
    x.parentNode.removeChild(x);    //this prevents the error
  }

  b.appendChild(x);
```

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
