### ISSUE TITLE
Unable to get property 'capture' of null in IE11

### ISSUE THREAD

**Issue by mferster** [webcomponents/webcomponentsjs#860]
I'm getting an unable to get property 'capture' of null error in IE11 from webcomponents-lite.js, though I get no error in chrome.
I'm running Angular 4.6 and Typescript.

```
function kc(a,b,c){
   if(b){
      if("object"===typeof c){
         var d=!!c.capture; // <== exception thrown here
         ...
```

I created a monkey patch to add a check for null to the 'if' condition, and it fixed the page and made the error go away, at least for IE11. See below...

```
function kc(a,b,c){
   if(b){
      if(c&&"object"===typeof c){
         var d=!!c.capture;
         ...
```

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
