### ISSUE TITLE
IE super class exception

### ISSUE THREAD

**Issue by northkode** [webcomponents/webcomponentsjs#865]
So i feel like i've tried everything, but i can't get even a simple component to work in IE 11

my code looks like this 

```import {
    WebComponent
} from "web-component";

@WebComponent("survey-form", {
    template: 'test',
    styles: '',
    shadowDOM: false
})
export default class component extends HTMLElement {
    constructor() {
        super();

        console.log('test')
    }

}
```

compile everything with babelrc and webpack

i have attached an error from ie 11

```{
    "presets": ["es2015-ie", "stage-1", "stage-2"],
    "plugins": ["transform-decorators-legacy"]
}
```

i load in the webcomponents-lite.js

but this is the error i keep getting. 

can someone please help?

![screenshot 2017-11-06 15 34 02](https://user-images.githubusercontent.com/6988083/32467469-e0b3498c-c307-11e7-9988-98ce34dac851.png)

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
