### ISSUE TITLE
firefox load issues

### ISSUE THREAD

**Issue by baremetalcomponents** [webcomponents/webcomponentsjs#867]
playing around with web components, I thought I would try and use it in browsers other than chrome. Got a simple demo going but it does not seem to work  on firefox.

https://github.com/baremetalcomponents/async-image

On chrome and safri it works fine, showing the two images as expected, but on firefox the 'WebComponentsReady' does not fire, nor does the components attributeChangedCallback, though the components connectedCallback does seem to fire.

Is this a problem on the polyfil side or firefox as such.

**Comment by ernsheong** [comment]
@baremetalcomponents Please see comments in https://github.com/webcomponents/webcomponentsjs/issues/846 and see if it fixes your problem. 

Your application needs to load AFTER the `WebComponentsReady` event.

**Comment by TimvdLippe** [comment]
Even if you listen for that event, because you made the `HTML import` async, the definition is not guaranteed to be there. You have 2 options: do not make the import async or use [`customElements.whenDefined`](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/whenDefined) to be notified when the definitions have been loaded.
