### ISSUE TITLE
IE11 Error with Polymer - SCRIPT5022: SyntaxError on File: webcomponents-lite.js

### ISSUE THREAD

**Issue by ashenwgt** [webcomponents/webcomponentsjs#873]
I made a Polymer app using default **polymer starter kit** template. It works well on Chrome and Firefox. But when I test it on **IE11** using **es5-bundled-preset** served via **PRPL-Server-Node**, it throws the following errors in browser debugger.
![1](https://user-images.githubusercontent.com/14919989/33645338-49ac6ae8-da70-11e7-8015-6bb5e3055d70.png)
![2](https://user-images.githubusercontent.com/14919989/33645350-523cc464-da70-11e7-85ee-bee297948aec.png)

When I check browser console:
![3](https://user-images.githubusercontent.com/14919989/33645387-9261bfb8-da70-11e7-8a28-60854c2bc1a4.png)

Here's how the network section looks:
![4](https://user-images.githubusercontent.com/14919989/33645416-b7582992-da70-11e7-9ca5-467ba114207f.PNG)

I'm using the following versions of bower dependencies:
![5](https://user-images.githubusercontent.com/14919989/33645938-5f79dc54-da73-11e7-9b37-6b333c373ca1.PNG)

And my polymer.json specification looks like below:
![6](https://user-images.githubusercontent.com/14919989/33645467-fcf40034-da70-11e7-9099-f185e04f38cd.PNG)

I tried to fix this for days, but the issue is still there. Am I missing something with the support of polyfills in polymer on IE11 or is this a bug in webcomponentsjs dependency?

**Comment by cwenzelg** [comment]
i have exactly the same syntax errors, same case. all working except IE. still trying to figure out what element could through them. I also have them with the new version 1.0.21.

**Comment by ashenwgt** [comment]
Hey @cwenzelg , do you use the JavaScript files (.js) inside the Polymer files (.html)? In my project, I can see that when I stop calling pure JS files, all errors disappear. But I am not really sure of this workaround and don't have any logical explanation on how it works. And now I am wondering whether we have to convert all the JS files and libs to Polymer components. Can someone confirm this behavior?

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
