### ISSUE TITLE
IE 11: disconnectedCallback is not called

### ISSUE THREAD

**Issue by dleistn1** [webcomponents/webcomponentsjs#875]
Hi,
there is a problem with Internet Explorer 11: it seems that the disconnectedCallback is not called on disconnection of an element via set of the innerHTML property of the parent that contains it. connectedCallback is running as expected. In Firefox (57.0.1) and Edge the disconnectedCallback is properly executed. Maybe this has something to do with the asynchronous implementation of the callbacks?

Best regards
Dan

**Comment by dleistn1** [comment]
Any updates on this?

**Comment by tcerno** [comment]
The problem occurs for custom elements that are loaded into a node via ajax and removed later when innerHTML has been updated. 
We have found a solution for this to make it work in IE 11. You have to remove all child nodes with [removeChild()](https://developer.mozilla.org/de/docs/Web/API/Node/removeChild) before setting new content with innerHTML.

**Comment by php1990** [comment]
I'm facing the same issue. Although the workaround to use [removeChild()](https://developer.mozilla.org/de/docs/Web/API/Node/removeChild) works fine, it would be great if disconnectedCallback also works with innerHTML property. Please let us know if there's an update on this.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
