### ISSUE TITLE
Html import error on Safari 11.0.2

### ISSUE THREAD

**Issue by NeilujD** [webcomponents/webcomponentsjs#885]
I am working on a Polymer 2 project.
I use the `polymer build` command with the `es5-bundled` preset to build my project before deploy to a Firebase app.
I use `webcomponents-loader.js` to make my app work on most of browsers.
It work perfectly with Chrome but I still get a very blocking issue on Safari 11.0.2 and on iOS too.
Here is a stack of the error :
```
[Error] TypeError: null is not an object (evaluating 'l.parentNode.replaceChild') (html-imports.js:431)
	b (html-imports.js:431)
	(fonction anonyme) (html-imports.js:434)
	c (html-imports.js:568)
```

The result of this is a blank page.
It is been a while since I get this error and I really need my app to work on Safari.
Can anyone help me on that ?
Please ask if you need more infos.

Edit:
It seems like when I do not try to bundle there is no issues at least on Safari 11.0.2 but still does it mean that older browsers won't support it ?

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
