### ISSUE TITLE
Polymer 3 Problem with elements not being upgraded

### ISSUE THREAD

**Issue by EliArtist** [webcomponents/webcomponentsjs#897]
I experienced some weird error I couldnt solve for days now. I'm using Polymer 3 with Meteor 1.6.1 and I got no errors on chrome/chromium and firefox nightly. But its a whole other story with the current official firefox release.
`Error: The custom element constructor did not produce the element being upgraded. (CustomElementInternals.js)`
I'm using webcomponents v1.1.0.
Anyone any idea?
If more information is needed, I'll provide it.

**Comment by EliArtist** [comment]
Update: I tried around quite a bit and came to the conclusion, that it's a problem with Polymer 3.0-preview WebComponents. And its just a Firefox problem, that should be solved with Firefox 60.

**Comment by tprzytula** [comment]
@EliArtist 

Hi, could you give some tips how to make Meteor 1.6.1 work with Polymer 3?
I'm really interested in it.

**Comment by yorrd** [comment]
hey @tprzytula , I'm @EliArtist 's colleague. We wrote an issue on the Meteor issue tracker concerning this which also contains our current workaround. Please let me know if this works for you. We'd be happy to collaborate on this. We boys gotta stick together, there is literally nobody else using that combo, but I love it ;) 

https://github.com/meteor/meteor/issues/9717

**Comment by tprzytula** [comment]
@yorrd 

Sorry for the late response!
Good job! Nice to see your approach 👍 

Actually we are migrating currently from Polymer 1 to Polymer 2 instead of 3.
During looking for some ideas how to approach this I saw your issue and thought that it's a great opportunity to look even more ahead and ask for details :) My curiosity was really strong in this one.

We won't move into Polymer 3 in the near future but it's great to see you guys moving forward!

Good luck with it, if at some point I will also work with Meteor + Polymer 3 then for sure I will also share some insight.

**Comment by formspoint** [comment]
3 is out, any successful integrations to speak of?
