### ISSUE TITLE
Improve Bower support for all polyfills

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponentsjs#91]
<a href="https://github.com/pennyfx"><img src="https://avatars.githubusercontent.com/u/224857?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pennyfx](https://github.com/pennyfx)**
_Wednesday Apr 23, 2014 at 14:40 GMT_
_Originally opened as https://github.com/Polymer/HTMLImports/issues/59_

---

I installed `Polymer/HTMLImports` via Bower and it works as long as you make your bower_components directory public.  

For X-Tag components we use the bower dependency tree and the `main:` property to figure out which files are needed for each library.   This doesn't work with these polyfills because of your custom loader.  For example, HTMLImports `main:` points to html-imports.js and it's a dead end.  Bower brings in the correct dependencies, but `loader` and `Weakmap` do not have a `main:`, so I'm stuck.    

Can you make sure that all libraries registered with Bower have a `main:`, so we can programmatically resolve dependencies using `bower list --json`?

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
