### ISSUE TITLE
Allow users for force use of the polyfill

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponentsjs#92]
<a href="https://github.com/sorvell"><img src="https://avatars.githubusercontent.com/u/78891?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sorvell](https://github.com/sorvell)**
_Tuesday Aug 12, 2014 at 02:56 GMT_
_Originally opened as https://github.com/Polymer/HTMLImports/issues/71_

---

It's convenient for testing to be able to force the polyfill to be on. In particular Polymer platform's ShadowDOM style shimming only functions correctly with the HTMLImports polyfill.

Perhaps we could accomplish this by resetting the `rel="imports"` attribute on all imports to avoid them natively processing when in polyfill mode.

**Comment by garlicnation** [comment]
@sorvell is this issue important now that chrome has finished implementing Web Components standards?  As I understand it there are now only two supported configurations of the polyfills(ShadowDom+everything, or CustomElements+HTMLImports).

**Comment by warpech** [comment]
I am also interested in forcing Chrome to use webcomponentsjs polyfill. This will make Firefox debugging easier :) Is there any way to achieve that?

**Comment by warpech** [comment]
Specifically, I am interested in forcing Shadow DOM polyfill (not HTML Imports, as the OP)

**Comment by oskude** [comment]
Hmm, webcomponentsjs polyfill and Chromium (at least 57.0.2987.133 64-bit) seem to not implement the same thing(s). [This](https://github.com/oskude/test-ce-import) test using webcomponents-loader.js works in current Firefox but not in Chromium. (Chromium does not find the template tag in the importet html?)

Can someone confirm where the bug lies in that test?
(I'm guessing it's chromiums native html-import that we can't overwrite nor disable?)

**Comment by TimvdLippe** [comment]
Since HTML Imports are not going further as a standard, we are no longer pursueing this issue.
