### ISSUE TITLE
Edge 17.134 Unable to set property 'innerHTML' of undefined or null reference

### ISSUE THREAD

**Issue by ruud** [webcomponents/webcomponentsjs#923]
New version of Edge 17, is causing problems accessing the template during the connectedCallback using Polymer version 2.6.0 and webcomponentsJS 1.2.0

**Note**: Edge 16 does not have this issue.

<img width="1004" alt="screen shot 2018-05-01 at 8 13 39 pm" src="https://user-images.githubusercontent.com/28245/39486397-3f55d280-4d7c-11e8-97c2-f56effc11e5f.png">

**Comment by ruud** [comment]
Probable root cause: Edge has broken fragment cloning which means you cannot clone template.content. That's why the polyfill was forced in the web component loader. This mechanism is not working for Edge 17. When added an extra browser check to the loader fixes this problem.

**Comment by ruud** [comment]
As far as i understand, the template polyfill should also be forced for edge 17. Now it is bypassed by the webcomponent loader.

**Comment by sorvell** [comment]
It looks like the issue is [here](https://github.com/webcomponents/webcomponentsjs/blob/master/webcomponents-loader.js#L33).

There are 2 problems in Edge: (1) DocumentFragment cloning is broken, (2) Template cloning is broken. Edge 17 fixes (1) but not (2) and the loader is only checking (1) to see if the Template polyfill should load.

**Comment by sorvell** [comment]
As a workaround, you can, of course, use `webcomponents-lite.js` instead of the loader, but that may have been obvious. We'll work on a fix.
