### ISSUE TITLE
Chrome webview sez Uncaught TypeError: Cannot read property 'length' of null Loader.js 110

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponentsjs#93]
<a href="https://github.com/elsigh"><img src="https://avatars.githubusercontent.com/u/517210?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [elsigh](https://github.com/elsigh)**
_Saturday Nov 22, 2014 at 00:36 GMT_
_Originally opened as https://github.com/Polymer/HTMLImports/issues/83_

---

This is in a Cordova app. Looks like there's a loop over something that's null.

**Comment by garlicnation** [comment]
@elsigh can you provide an example?

**Comment by elsigh** [comment]
I don't have one, but I suspect that one could take the hello world cordova app, make the index page be a simple polymer app, and get this exception.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
