### ISSUE TITLE
Error in Chromium

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponentsjs#97]
<a href="https://github.com/nazar-pc"><img src="https://avatars.githubusercontent.com/u/928965?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nazar-pc](https://github.com/nazar-pc)**
_Sunday Aug 31, 2014 at 20:19 GMT_
_Originally opened as https://github.com/Polymer/CustomElements/issues/127_

----

> Uncaught TypeError: Cannot read property 'register' of undefined

This is about line: https://github.com/Polymer/CustomElements/blob/544c8a0fd0bb0940bf3f1262ba9573e787d9cbd5/src/CustomElements.js#L34

Chromium 36.0.1985.143 Ubuntu 14.10 (287914)

**Comment by mararenzsmith** [comment]
What is platform.js?

**Comment by addyosmani** [comment]
platform.js is the old name of webcomponents.js.

**Comment by mararenzsmith** [comment]
Okay, I'm getting the same error but I definitely am loading webcomponents.js before polymer.html

**Comment by aeroxy** [comment]
Wow awesome thanks tjsavage.

**Comment by garlicnation** [comment]
@mararenzsmith  It's possible that a syntax error in your element definition is causing this. Polymer can sometimes display unhelpful messages in that case. If you're still experiencing issues, open a new issue with more context and I'd be happy to take a look at it.

@tjsavage We have to make sure that 0.8 and forward produce nicer error messages when source fails to parse. Is it happening because we're eval'ing code from the imports?
