### ISSUE TITLE
IDs within shadow root leaks

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponentsjs#99]
<a href="https://github.com/arv"><img src="https://avatars.githubusercontent.com/u/45845?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [arv](https://github.com/arv)**
_Monday Jun 10, 2013 at 15:02 GMT_
_Originally opened as https://github.com/Polymer/ShadowDOM/issues/157_

---

We are currently doing `getElementsById` on the composed DOM so we might end up with ID conflicts.

Similar issues exists for `labelFor`, aria attributes as well as links pointing to ID refs.

**Comment by RichCaloggero** [comment]
Hoping this gets fixed soon!

Love webcomponents, but without proper ID encapsulation, `aria` becomes burdensome.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
